/**
 * Default Field Configurations
 * 
 * Default field configurations for each database type.
 */

import { FieldConfiguration, DatabaseTypeInfo } from '../types/fieldConfig';

export const DATABASE_TYPES: DatabaseTypeInfo[] = [
  { id: 'mongodb', name: 'MongoDB', icon: '🍃' },
  { id: 'documentdb', name: 'DocumentDB', icon: '📄' },
  { id: 'postgresql', name: 'PostgreSQL', icon: '🐘' },
  { id: 'mysql', name: 'MySQL', icon: '🐬' },
  { id: 'oracle', name: 'Oracle', icon: '🔴' },
  { id: 'sqlserver', name: 'SQL Server', icon: '🔷' },
  { id: 'bigquery', name: 'BigQuery', icon: '☁️' },
  { id: 'redshift', name: 'Amazon Redshift', icon: '🔺' },
];

export const MONGODB_DEFAULT_FIELDS: FieldConfiguration[] = [
  {
    id: 'mongodb-host',
    name: 'host',
    label: 'Host',
    type: 'text',
    enabled: true,
    required: true,
    placeholder: 'localhost',
    displayOrder: 1,
    databaseType: 'mongodb',
  },
  {
    id: 'mongodb-port',
    name: 'port',
    label: 'Port',
    type: 'number',
    enabled: true,
    required: true,
    defaultValue: '27017',
    displayOrder: 2,
    databaseType: 'mongodb',
  },
  {
    id: 'mongodb-database',
    name: 'database',
    label: 'Database',
    type: 'text',
    enabled: true,
    required: true,
    displayOrder: 3,
    databaseType: 'mongodb',
  },
  {
    id: 'mongodb-username',
    name: 'username',
    label: 'Username',
    type: 'text',
    enabled: true,
    required: false,
    displayOrder: 4,
    databaseType: 'mongodb',
  },
  {
    id: 'mongodb-password',
    name: 'password',
    label: 'Password',
    type: 'password',
    enabled: true,
    required: false,
    displayOrder: 5,
    databaseType: 'mongodb',
  },
  {
    id: 'mongodb-replica-set',
    name: 'replica_set',
    label: 'Replica Set',
    type: 'text',
    enabled: true,
    required: false,
    helpText: 'Name of the replica set',
    displayOrder: 6,
    databaseType: 'mongodb',
  },
  {
    id: 'mongodb-auth-database',
    name: 'auth_database',
    label: 'Authentication Database',
    type: 'text',
    enabled: true,
    required: false,
    defaultValue: 'admin',
    displayOrder: 7,
    databaseType: 'mongodb',
  },
];

export const DOCUMENTDB_DEFAULT_FIELDS: FieldConfiguration[] = [
  {
    id: 'documentdb-host',
    name: 'host',
    label: 'Host',
    type: 'text',
    enabled: true,
    required: true,
    placeholder: 'cluster.region.docdb.amazonaws.com',
    displayOrder: 1,
    databaseType: 'documentdb',
  },
  {
    id: 'documentdb-port',
    name: 'port',
    label: 'Port',
    type: 'number',
    enabled: true,
    required: true,
    defaultValue: '27017',
    displayOrder: 2,
    databaseType: 'documentdb',
  },
  {
    id: 'documentdb-database',
    name: 'database',
    label: 'Database',
    type: 'text',
    enabled: true,
    required: true,
    displayOrder: 3,
    databaseType: 'documentdb',
  },
  {
    id: 'documentdb-username',
    name: 'username',
    label: 'Username',
    type: 'text',
    enabled: true,
    required: true,
    displayOrder: 4,
    databaseType: 'documentdb',
  },
  {
    id: 'documentdb-password',
    name: 'password',
    label: 'Password',
    type: 'password',
    enabled: true,
    required: true,
    displayOrder: 5,
    databaseType: 'documentdb',
  },
  {
    id: 'documentdb-tls',
    name: 'tls',
    label: 'Enable TLS',
    type: 'checkbox',
    enabled: true,
    required: false,
    defaultValue: 'true',
    helpText: 'TLS is required for DocumentDB',
    displayOrder: 6,
    databaseType: 'documentdb',
  },
];

export const POSTGRESQL_DEFAULT_FIELDS: FieldConfiguration[] = [
  {
    id: 'postgresql-host',
    name: 'host',
    label: 'Host',
    type: 'text',
    enabled: true,
    required: true,
    placeholder: 'localhost',
    displayOrder: 1,
    databaseType: 'postgresql',
  },
  {
    id: 'postgresql-port',
    name: 'port',
    label: 'Port',
    type: 'number',
    enabled: true,
    required: true,
    defaultValue: '5432',
    displayOrder: 2,
    databaseType: 'postgresql',
  },
  {
    id: 'postgresql-database',
    name: 'database',
    label: 'Database',
    type: 'text',
    enabled: true,
    required: true,
    displayOrder: 3,
    databaseType: 'postgresql',
  },
  {
    id: 'postgresql-username',
    name: 'username',
    label: 'Username',
    type: 'text',
    enabled: true,
    required: true,
    displayOrder: 4,
    databaseType: 'postgresql',
  },
  {
    id: 'postgresql-password',
    name: 'password',
    label: 'Password',
    type: 'password',
    enabled: true,
    required: true,
    displayOrder: 5,
    databaseType: 'postgresql',
  },
  {
    id: 'postgresql-ssl-mode',
    name: 'ssl_mode',
    label: 'SSL Mode',
    type: 'select',
    enabled: true,
    required: false,
    defaultValue: 'prefer',
    helpText: 'SSL connection mode',
    displayOrder: 6,
    databaseType: 'postgresql',
  },
  {
    id: 'postgresql-schema',
    name: 'schema',
    label: 'Schema',
    type: 'text',
    enabled: true,
    required: false,
    defaultValue: 'public',
    displayOrder: 7,
    databaseType: 'postgresql',
  },
];

export const MYSQL_DEFAULT_FIELDS: FieldConfiguration[] = [
  {
    id: 'mysql-host',
    name: 'host',
    label: 'Host',
    type: 'text',
    enabled: true,
    required: true,
    placeholder: 'localhost',
    displayOrder: 1,
    databaseType: 'mysql',
  },
  {
    id: 'mysql-port',
    name: 'port',
    label: 'Port',
    type: 'number',
    enabled: true,
    required: true,
    defaultValue: '3306',
    displayOrder: 2,
    databaseType: 'mysql',
  },
  {
    id: 'mysql-database',
    name: 'database',
    label: 'Database',
    type: 'text',
    enabled: true,
    required: true,
    displayOrder: 3,
    databaseType: 'mysql',
  },
  {
    id: 'mysql-username',
    name: 'username',
    label: 'Username',
    type: 'text',
    enabled: true,
    required: true,
    displayOrder: 4,
    databaseType: 'mysql',
  },
  {
    id: 'mysql-password',
    name: 'password',
    label: 'Password',
    type: 'password',
    enabled: true,
    required: true,
    displayOrder: 5,
    databaseType: 'mysql',
  },
  {
    id: 'mysql-charset',
    name: 'charset',
    label: 'Character Set',
    type: 'text',
    enabled: true,
    required: false,
    defaultValue: 'utf8mb4',
    displayOrder: 6,
    databaseType: 'mysql',
  },
];

export const ORACLE_DEFAULT_FIELDS: FieldConfiguration[] = [
  {
    id: 'oracle-host',
    name: 'host',
    label: 'Host',
    type: 'text',
    enabled: true,
    required: true,
    placeholder: 'localhost',
    displayOrder: 1,
    databaseType: 'oracle',
  },
  {
    id: 'oracle-port',
    name: 'port',
    label: 'Port',
    type: 'number',
    enabled: true,
    required: true,
    defaultValue: '1521',
    displayOrder: 2,
    databaseType: 'oracle',
  },
  {
    id: 'oracle-sid',
    name: 'sid',
    label: 'SID',
    type: 'text',
    enabled: true,
    required: false,
    helpText: 'Oracle System Identifier',
    displayOrder: 3,
    databaseType: 'oracle',
  },
  {
    id: 'oracle-service-name',
    name: 'service_name',
    label: 'Service Name',
    type: 'text',
    enabled: true,
    required: false,
    helpText: 'Oracle Service Name',
    displayOrder: 4,
    databaseType: 'oracle',
  },
  {
    id: 'oracle-username',
    name: 'username',
    label: 'Username',
    type: 'text',
    enabled: true,
    required: true,
    displayOrder: 5,
    databaseType: 'oracle',
  },
  {
    id: 'oracle-password',
    name: 'password',
    label: 'Password',
    type: 'password',
    enabled: true,
    required: true,
    displayOrder: 6,
    databaseType: 'oracle',
  },
];

export const SQLSERVER_DEFAULT_FIELDS: FieldConfiguration[] = [
  {
    id: 'sqlserver-host',
    name: 'host',
    label: 'Host',
    type: 'text',
    enabled: true,
    required: true,
    placeholder: 'localhost',
    displayOrder: 1,
    databaseType: 'sqlserver',
  },
  {
    id: 'sqlserver-port',
    name: 'port',
    label: 'Port',
    type: 'number',
    enabled: true,
    required: true,
    defaultValue: '1433',
    displayOrder: 2,
    databaseType: 'sqlserver',
  },
  {
    id: 'sqlserver-database',
    name: 'database',
    label: 'Database',
    type: 'text',
    enabled: true,
    required: true,
    displayOrder: 3,
    databaseType: 'sqlserver',
  },
  {
    id: 'sqlserver-instance-name',
    name: 'instance_name',
    label: 'Instance Name',
    type: 'text',
    enabled: true,
    required: false,
    helpText: 'SQL Server instance name',
    displayOrder: 4,
    databaseType: 'sqlserver',
  },
  {
    id: 'sqlserver-username',
    name: 'username',
    label: 'Username',
    type: 'text',
    enabled: true,
    required: false,
    displayOrder: 5,
    databaseType: 'sqlserver',
  },
  {
    id: 'sqlserver-password',
    name: 'password',
    label: 'Password',
    type: 'password',
    enabled: true,
    required: false,
    displayOrder: 6,
    databaseType: 'sqlserver',
  },
  {
    id: 'sqlserver-windows-auth',
    name: 'windows_auth',
    label: 'Use Windows Authentication',
    type: 'checkbox',
    enabled: true,
    required: false,
    defaultValue: 'false',
    displayOrder: 7,
    databaseType: 'sqlserver',
  },
];

export const BIGQUERY_DEFAULT_FIELDS: FieldConfiguration[] = [
  {
    id: 'bigquery-project-id',
    name: 'project_id',
    label: 'Project ID',
    type: 'text',
    enabled: true,
    required: true,
    placeholder: 'my-gcp-project',
    helpText: 'Google Cloud Project ID',
    displayOrder: 1,
    databaseType: 'bigquery',
  },
  {
    id: 'bigquery-dataset',
    name: 'dataset',
    label: 'Dataset',
    type: 'text',
    enabled: true,
    required: true,
    placeholder: 'my_dataset',
    helpText: 'BigQuery dataset name',
    displayOrder: 2,
    databaseType: 'bigquery',
  },
  {
    id: 'bigquery-credentials-json',
    name: 'credentials_json',
    label: 'Service Account JSON',
    type: 'text',
    enabled: true,
    required: true,
    placeholder: 'Paste service account JSON key',
    helpText: 'Google Cloud service account credentials in JSON format',
    displayOrder: 3,
    databaseType: 'bigquery',
  },
  {
    id: 'bigquery-location',
    name: 'location',
    label: 'Location',
    type: 'text',
    enabled: true,
    required: false,
    defaultValue: 'US',
    placeholder: 'US, EU, asia-northeast1',
    helpText: 'BigQuery dataset location',
    displayOrder: 4,
    databaseType: 'bigquery',
  },
];

export const REDSHIFT_DEFAULT_FIELDS: FieldConfiguration[] = [
  {
    id: 'redshift-host',
    name: 'host',
    label: 'Host / Cluster Endpoint',
    type: 'text',
    enabled: true,
    required: true,
    placeholder: 'cluster.region.redshift.amazonaws.com',
    helpText: 'Redshift cluster endpoint',
    displayOrder: 1,
    databaseType: 'redshift',
  },
  {
    id: 'redshift-port',
    name: 'port',
    label: 'Port',
    type: 'number',
    enabled: true,
    required: true,
    defaultValue: '5439',
    displayOrder: 2,
    databaseType: 'redshift',
  },
  {
    id: 'redshift-database',
    name: 'database',
    label: 'Database',
    type: 'text',
    enabled: true,
    required: true,
    placeholder: 'dev',
    displayOrder: 3,
    databaseType: 'redshift',
  },
  {
    id: 'redshift-username',
    name: 'username',
    label: 'Username',
    type: 'text',
    enabled: true,
    required: true,
    displayOrder: 4,
    databaseType: 'redshift',
  },
  {
    id: 'redshift-password',
    name: 'password',
    label: 'Password',
    type: 'password',
    enabled: true,
    required: true,
    displayOrder: 5,
    databaseType: 'redshift',
  },
  {
    id: 'redshift-schema',
    name: 'schema',
    label: 'Schema',
    type: 'text',
    enabled: true,
    required: false,
    defaultValue: 'public',
    displayOrder: 6,
    databaseType: 'redshift',
  },
  {
    id: 'redshift-ssl',
    name: 'ssl',
    label: 'Enable SSL',
    type: 'checkbox',
    enabled: true,
    required: false,
    defaultValue: 'true',
    helpText: 'Use SSL for secure connection',
    displayOrder: 7,
    databaseType: 'redshift',
  },
];

export const DEFAULT_FIELD_CONFIGS: Record<string, FieldConfiguration[]> = {
  mongodb: MONGODB_DEFAULT_FIELDS,
  documentdb: DOCUMENTDB_DEFAULT_FIELDS,
  postgresql: POSTGRESQL_DEFAULT_FIELDS,
  mysql: MYSQL_DEFAULT_FIELDS,
  oracle: ORACLE_DEFAULT_FIELDS,
  sqlserver: SQLSERVER_DEFAULT_FIELDS,
  bigquery: BIGQUERY_DEFAULT_FIELDS,
  redshift: REDSHIFT_DEFAULT_FIELDS,
};
