"""
Default Field Configurations
Default field configurations for each database type
"""

BIGQUERY_DEFAULT_FIELDS = [
    {
        'id': 'bigquery-project-id',
        'name': 'project_id',
        'label': 'Project ID',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'my-gcp-project',
        'helpText': 'Google Cloud Project ID',
        'displayOrder': 1,
    },
    {
        'id': 'bigquery-dataset',
        'name': 'dataset',
        'label': 'Dataset',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'my_dataset',
        'helpText': 'BigQuery dataset name',
        'displayOrder': 2,
    },
    {
        'id': 'bigquery-credentials-json',
        'name': 'credentials_json',
        'label': 'Service Account JSON',
        'type': 'textarea',
        'enabled': True,
        'required': True,
        'placeholder': 'Paste service account JSON key',
        'helpText': 'Google Cloud service account credentials in JSON format',
        'displayOrder': 3,
    },
    {
        'id': 'bigquery-location',
        'name': 'location',
        'label': 'Location',
        'type': 'text',
        'enabled': True,
        'required': False,
        'defaultValue': 'US',
        'placeholder': 'US, EU, asia-northeast1',
        'helpText': 'BigQuery dataset location',
        'displayOrder': 4,
    },
]

MONGODB_DEFAULT_FIELDS = [
    {
        'id': 'mongodb-host',
        'name': 'host',
        'label': 'Host',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'localhost',
        'displayOrder': 1,
    },
    {
        'id': 'mongodb-port',
        'name': 'port',
        'label': 'Port',
        'type': 'number',
        'enabled': True,
        'required': True,
        'defaultValue': '27017',
        'displayOrder': 2,
    },
    {
        'id': 'mongodb-database',
        'name': 'database',
        'label': 'Database',
        'type': 'text',
        'enabled': True,
        'required': True,
        'displayOrder': 3,
    },
    {
        'id': 'mongodb-username',
        'name': 'username',
        'label': 'Username',
        'type': 'text',
        'enabled': True,
        'required': False,
        'displayOrder': 4,
    },
    {
        'id': 'mongodb-password',
        'name': 'password',
        'label': 'Password',
        'type': 'password',
        'enabled': True,
        'required': False,
        'displayOrder': 5,
    },
]

REDSHIFT_DEFAULT_FIELDS = [
    {
        'id': 'redshift-server-name',
        'name': 'server_name',
        'label': 'Server Name',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'my-cluster.abc123.us-east-1.redshift.amazonaws.com',
        'helpText': 'Amazon Redshift cluster endpoint',
        'displayOrder': 1,
    },
    {
        'id': 'redshift-port',
        'name': 'port',
        'label': 'Port',
        'type': 'number',
        'enabled': True,
        'required': True,
        'defaultValue': '5439',
        'helpText': 'Redshift port number (default: 5439)',
        'displayOrder': 2,
    },
    {
        'id': 'redshift-username',
        'name': 'username',
        'label': 'Username',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'admin',
        'helpText': 'Redshift database user',
        'displayOrder': 3,
    },
    {
        'id': 'redshift-password',
        'name': 'password',
        'label': 'Password',
        'type': 'password',
        'enabled': True,
        'required': True,
        'helpText': 'Redshift database password',
        'displayOrder': 4,
    },
    {
        'id': 'redshift-database',
        'name': 'database_name',
        'label': 'Database',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'mydb',
        'helpText': 'Name of the Redshift database',
        'displayOrder': 5,
    },
]

DOCUMENTDB_DEFAULT_FIELDS = [
    {
        'id': 'documentdb-host',
        'name': 'host',
        'label': 'Cluster Endpoint',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'my-cluster.cluster-abc123.us-east-1.docdb.amazonaws.com',
        'helpText': 'DocumentDB cluster endpoint',
        'displayOrder': 1,
    },
    {
        'id': 'documentdb-port',
        'name': 'port',
        'label': 'Port',
        'type': 'number',
        'enabled': True,
        'required': True,
        'defaultValue': '27017',
        'helpText': 'DocumentDB port (default: 27017)',
        'displayOrder': 2,
    },
    {
        'id': 'documentdb-database',
        'name': 'database',
        'label': 'Database',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'mydb',
        'displayOrder': 3,
    },
    {
        'id': 'documentdb-username',
        'name': 'username',
        'label': 'Username',
        'type': 'text',
        'enabled': True,
        'required': True,
        'displayOrder': 4,
    },
    {
        'id': 'documentdb-password',
        'name': 'password',
        'label': 'Password',
        'type': 'password',
        'enabled': True,
        'required': True,
        'displayOrder': 5,
    },
    {
        'id': 'documentdb-tls',
        'name': 'tls_enabled',
        'label': 'TLS Enabled',
        'type': 'checkbox',
        'enabled': True,
        'required': False,
        'defaultValue': True,
        'helpText': 'Enable TLS/SSL connection',
        'displayOrder': 6,
    },
    {
        'id': 'documentdb-ca-file',
        'name': 'tls_ca_file',
        'label': 'TLS CA Certificate',
        'type': 'textarea',
        'enabled': True,
        'required': False,
        'placeholder': 'Paste CA certificate content',
        'helpText': 'AWS DocumentDB CA certificate for TLS',
        'displayOrder': 7,
    },
]

# Add more database types as needed...

DEFAULT_CONFIGS = {
    'bigquery': BIGQUERY_DEFAULT_FIELDS,
    'mongodb': MONGODB_DEFAULT_FIELDS,
    'redshift': REDSHIFT_DEFAULT_FIELDS,
    'documentdb': DOCUMENTDB_DEFAULT_FIELDS,
    # Add more as needed
}


def get_default_configs(database_type: str):
    """Get default configurations for a database type"""
    return DEFAULT_CONFIGS.get(database_type, [])
