"""
Default Field Configurations
Default field configurations for each database type
"""

BIGQUERY_DEFAULT_FIELDS = [
    {
        'id': 'bigquery-project-id',
        'name': 'project_id',
        'label': 'Project ID',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'my-gcp-project',
        'helpText': 'Google Cloud Project ID',
        'displayOrder': 1,
    },
    {
        'id': 'bigquery-dataset',
        'name': 'dataset',
        'label': 'Dataset',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'my_dataset',
        'helpText': 'BigQuery dataset name',
        'displayOrder': 2,
    },
    {
        'id': 'bigquery-credentials-json',
        'name': 'credentials_json',
        'label': 'Service Account JSON',
        'type': 'textarea',
        'enabled': True,
        'required': True,
        'placeholder': 'Paste service account JSON key',
        'helpText': 'Google Cloud service account credentials in JSON format',
        'displayOrder': 3,
    },
    {
        'id': 'bigquery-location',
        'name': 'location',
        'label': 'Location',
        'type': 'text',
        'enabled': True,
        'required': False,
        'defaultValue': 'US',
        'placeholder': 'US, EU, asia-northeast1',
        'helpText': 'BigQuery dataset location',
        'displayOrder': 4,
    },
]

MONGODB_DEFAULT_FIELDS = [
    {
        'id': 'mongodb-host',
        'name': 'host',
        'label': 'Host',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'localhost',
        'displayOrder': 1,
    },
    {
        'id': 'mongodb-port',
        'name': 'port',
        'label': 'Port',
        'type': 'number',
        'enabled': True,
        'required': True,
        'defaultValue': '27017',
        'displayOrder': 2,
    },
    {
        'id': 'mongodb-database',
        'name': 'database',
        'label': 'Database',
        'type': 'text',
        'enabled': True,
        'required': True,
        'displayOrder': 3,
    },
    {
        'id': 'mongodb-username',
        'name': 'username',
        'label': 'Username',
        'type': 'text',
        'enabled': True,
        'required': False,
        'displayOrder': 4,
    },
    {
        'id': 'mongodb-password',
        'name': 'password',
        'label': 'Password',
        'type': 'password',
        'enabled': True,
        'required': False,
        'displayOrder': 5,
    },
]

REDSHIFT_DEFAULT_FIELDS = [
    {
        'id': 'redshift-server-name',
        'name': 'server_name',
        'label': 'Server Name',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'my-cluster.abc123.us-east-1.redshift.amazonaws.com',
        'helpText': 'Amazon Redshift cluster endpoint',
        'displayOrder': 1,
    },
    {
        'id': 'redshift-port',
        'name': 'port',
        'label': 'Port',
        'type': 'number',
        'enabled': True,
        'required': True,
        'defaultValue': '5439',
        'helpText': 'Redshift port number (default: 5439)',
        'displayOrder': 2,
    },
    {
        'id': 'redshift-username',
        'name': 'username',
        'label': 'Username',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'admin',
        'helpText': 'Redshift database user',
        'displayOrder': 3,
    },
    {
        'id': 'redshift-password',
        'name': 'password',
        'label': 'Password',
        'type': 'password',
        'enabled': True,
        'required': True,
        'helpText': 'Redshift database password',
        'displayOrder': 4,
    },
    {
        'id': 'redshift-database',
        'name': 'database_name',
        'label': 'Database',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'mydb',
        'helpText': 'Name of the Redshift database',
        'displayOrder': 5,
    },
]

DOCUMENTDB_DEFAULT_FIELDS = [
    {
        'id': 'documentdb-host',
        'name': 'host',
        'label': 'Cluster Endpoint',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'my-cluster.cluster-abc123.us-east-1.docdb.amazonaws.com',
        'helpText': 'DocumentDB cluster endpoint',
        'displayOrder': 1,
    },
    {
        'id': 'documentdb-port',
        'name': 'port',
        'label': 'Port',
        'type': 'number',
        'enabled': True,
        'required': True,
        'defaultValue': '27017',
        'helpText': 'DocumentDB port (default: 27017)',
        'displayOrder': 2,
    },
    {
        'id': 'documentdb-database',
        'name': 'database',
        'label': 'Database',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'mydb',
        'displayOrder': 3,
    },
    {
        'id': 'documentdb-username',
        'name': 'username',
        'label': 'Username',
        'type': 'text',
        'enabled': True,
        'required': True,
        'displayOrder': 4,
    },
    {
        'id': 'documentdb-password',
        'name': 'password',
        'label': 'Password',
        'type': 'password',
        'enabled': True,
        'required': True,
        'displayOrder': 5,
    },
    {
        'id': 'documentdb-tls',
        'name': 'tls_enabled',
        'label': 'TLS Enabled',
        'type': 'checkbox',
        'enabled': True,
        'required': False,
        'defaultValue': True,
        'helpText': 'Enable TLS/SSL connection',
        'displayOrder': 6,
    },
    {
        'id': 'documentdb-ca-file',
        'name': 'tls_ca_file',
        'label': 'TLS CA Certificate',
        'type': 'textarea',
        'enabled': True,
        'required': False,
        'placeholder': 'Paste CA certificate content',
        'helpText': 'AWS DocumentDB CA certificate for TLS',
        'displayOrder': 7,
    },
]

# Add more database types as needed...

SQLSERVER_DEFAULT_FIELDS = [
    {
        'id': 'sqlserver-host',
        'name': 'host',
        'label': 'Host',
        'type': 'text',
        'enabled': True,
        'required': True,
        'defaultValue': 'localhost',
        'placeholder': 'localhost',
        'helpText': 'SQL Server hostname or IP address',
        'displayOrder': 1,
    },
    {
        'id': 'sqlserver-port',
        'name': 'port',
        'label': 'Port',
        'type': 'number',
        'enabled': True,
        'required': True,
        'defaultValue': '1433',
        'helpText': 'SQL Server port (default: 1433)',
        'displayOrder': 2,
    },
    {
        'id': 'sqlserver-database',
        'name': 'database_name',
        'label': 'Database',
        'type': 'text',
        'enabled': True,
        'required': True,
        'defaultValue': 'master',
        'placeholder': 'master',
        'helpText': 'Database name to connect to',
        'displayOrder': 3,
    },
    {
        'id': 'sqlserver-instance',
        'name': 'instance_name',
        'label': 'Instance Name',
        'type': 'text',
        'enabled': True,
        'required': False,
        'defaultValue': 'SQLEXPRESS',
        'placeholder': 'SQLEXPRESS',
        'helpText': 'SQL Server named instance (leave empty for default instance)',
        'displayOrder': 4,
    },
    {
        'id': 'sqlserver-username',
        'name': 'username',
        'label': 'Username',
        'type': 'text',
        'enabled': True,
        'required': False,
        'placeholder': 'sa',
        'helpText': 'SQL Server login username',
        'displayOrder': 5,
    },
    {
        'id': 'sqlserver-password',
        'name': 'password',
        'label': 'Password',
        'type': 'password',
        'enabled': True,
        'required': False,
        'helpText': 'SQL Server login password',
        'displayOrder': 6,
    },
    {
        'id': 'sqlserver-windows-auth',
        'name': 'windows_auth',
        'label': 'Use Windows Authentication',
        'type': 'checkbox',
        'enabled': True,
        'required': False,
        'defaultValue': False,
        'helpText': 'Use Windows Authentication instead of SQL Server authentication',
        'displayOrder': 7,
    },
    {
        'id': 'sqlserver-odbc-driver',
        'name': 'odbc_driver',
        'label': 'ODBC Driver',
        'type': 'text',
        'enabled': True,
        'required': True,
        'defaultValue': 'ODBC Driver 17 for SQL Server',
        'placeholder': 'ODBC Driver 17 for SQL Server',
        'helpText': 'ODBC driver name installed on the system',
        'displayOrder': 8,
    },
]

SYBASE_DEFAULT_FIELDS = [
    {
        'id': 'sybase-host',
        'name': 'host',
        'label': 'Host',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'localhost',
        'helpText': 'SAP Sybase ASE hostname or IP address',
        'displayOrder': 1,
    },
    {
        'id': 'sybase-port',
        'name': 'port',
        'label': 'Port',
        'type': 'number',
        'enabled': True,
        'required': True,
        'defaultValue': '5000',
        'helpText': 'Sybase ASE port (default: 5000)',
        'displayOrder': 2,
    },
    {
        'id': 'sybase-database',
        'name': 'database_name',
        'label': 'Database',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'mydb',
        'helpText': 'Database name to connect to',
        'displayOrder': 3,
    },
    {
        'id': 'sybase-server-name',
        'name': 'server_name',
        'label': 'Server Name',
        'type': 'text',
        'enabled': True,
        'required': False,
        'placeholder': 'SYBASE',
        'helpText': 'Adaptive Server name (DSQUERY)',
        'displayOrder': 4,
    },
    {
        'id': 'sybase-username',
        'name': 'username',
        'label': 'Username',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'sa',
        'displayOrder': 5,
    },
    {
        'id': 'sybase-password',
        'name': 'password',
        'label': 'Password',
        'type': 'password',
        'enabled': True,
        'required': True,
        'displayOrder': 6,
    },
    {
        'id': 'sybase-charset',
        'name': 'charset',
        'label': 'Character Set',
        'type': 'text',
        'enabled': True,
        'required': False,
        'defaultValue': 'utf8',
        'helpText': 'Connection character set',
        'displayOrder': 7,
    },
]

DB2_DEFAULT_FIELDS = [
    {
        'id': 'db2-host',
        'name': 'host',
        'label': 'Host',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'localhost',
        'helpText': 'IBM Db2 hostname or IP address',
        'displayOrder': 1,
    },
    {
        'id': 'db2-port',
        'name': 'port',
        'label': 'Port',
        'type': 'number',
        'enabled': True,
        'required': True,
        'defaultValue': '50000',
        'helpText': 'Db2 port (default: 50000)',
        'displayOrder': 2,
    },
    {
        'id': 'db2-database',
        'name': 'database_name',
        'label': 'Database',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'SAMPLE',
        'helpText': 'Database name to connect to',
        'displayOrder': 3,
    },
    {
        'id': 'db2-schema',
        'name': 'schema',
        'label': 'Schema',
        'type': 'text',
        'enabled': True,
        'required': False,
        'helpText': 'Default schema name',
        'displayOrder': 4,
    },
    {
        'id': 'db2-username',
        'name': 'username',
        'label': 'Username',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'db2inst1',
        'displayOrder': 5,
    },
    {
        'id': 'db2-password',
        'name': 'password',
        'label': 'Password',
        'type': 'password',
        'enabled': True,
        'required': True,
        'displayOrder': 6,
    },
    {
        'id': 'db2-ssl',
        'name': 'ssl_enabled',
        'label': 'Enable SSL',
        'type': 'checkbox',
        'enabled': True,
        'required': False,
        'defaultValue': False,
        'helpText': 'Use SSL for secure connection',
        'displayOrder': 7,
    },
]

CLICKHOUSE_DEFAULT_FIELDS = [
    {
        'id': 'clickhouse-host',
        'name': 'host',
        'label': 'Host',
        'type': 'text',
        'enabled': True,
        'required': True,
        'placeholder': 'your-instance.clickhouse.cloud',
        'helpText': 'ClickHouse server hostname or IP address',
        'displayOrder': 1,
    },
    {
        'id': 'clickhouse-port',
        'name': 'port',
        'label': 'Port',
        'type': 'number',
        'enabled': True,
        'required': True,
        'defaultValue': '8443',
        'helpText': '8443 for HTTPS, 8123 for HTTP, 9440 for native secure',
        'displayOrder': 2,
    },
    {
        'id': 'clickhouse-database',
        'name': 'database_name',
        'label': 'Database',
        'type': 'text',
        'enabled': True,
        'required': True,
        'defaultValue': 'default',
        'placeholder': 'default',
        'helpText': 'ClickHouse database name',
        'displayOrder': 3,
    },
    {
        'id': 'clickhouse-username',
        'name': 'username',
        'label': 'Username',
        'type': 'text',
        'enabled': True,
        'required': True,
        'defaultValue': 'default',
        'placeholder': 'default',
        'helpText': 'ClickHouse username',
        'displayOrder': 4,
    },
    {
        'id': 'clickhouse-password',
        'name': 'password',
        'label': 'Password',
        'type': 'password',
        'enabled': True,
        'required': True,
        'helpText': 'ClickHouse password',
        'displayOrder': 5,
    },
    {
        'id': 'clickhouse-secure',
        'name': 'secure',
        'label': 'Use SSL/TLS',
        'type': 'checkbox',
        'enabled': True,
        'required': False,
        'defaultValue': 'true',
        'helpText': 'Enable SSL/TLS (required for ClickHouse Cloud)',
        'displayOrder': 6,
    },
]

DEFAULT_CONFIGS = {
    'bigquery': BIGQUERY_DEFAULT_FIELDS,
    'mongodb': MONGODB_DEFAULT_FIELDS,
    'redshift': REDSHIFT_DEFAULT_FIELDS,
    'clickhouse': CLICKHOUSE_DEFAULT_FIELDS,
    'documentdb': DOCUMENTDB_DEFAULT_FIELDS,
    'sqlserver': SQLSERVER_DEFAULT_FIELDS,
    'sybase': SYBASE_DEFAULT_FIELDS,
    'db2': DB2_DEFAULT_FIELDS,
}


def get_default_configs(database_type: str):
    """Get default configurations for a database type"""
    return DEFAULT_CONFIGS.get(database_type, [])
