import React, { createContext, useContext, useState, ReactNode } from 'react';

export type LanguageCode = 'en' | 'ko' | 'zh' | 'ja' | 'fr' | 'es' | 'de' | 'pt' | 'hi';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  labelEn: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', labelEn: 'English', flag: '🇺🇸' },
  { code: 'ko', label: '한국어', labelEn: 'Korean', flag: '🇰🇷' },
  { code: 'zh', label: '中文', labelEn: 'Chinese', flag: '🇨🇳' },
  { code: 'ja', label: '日本語', labelEn: 'Japanese', flag: '🇯🇵' },
  { code: 'fr', label: 'Français', labelEn: 'French', flag: '🇫🇷' },
  { code: 'es', label: 'Español', labelEn: 'Spanish', flag: '🇪🇸' },
  { code: 'de', label: 'Deutsch', labelEn: 'German', flag: '🇩🇪' },
  { code: 'pt', label: 'Português', labelEn: 'Portuguese', flag: '🇧🇷' },
  { code: 'hi', label: 'हिन्दी', labelEn: 'Hindi', flag: '🇮🇳' },
];

// Use Record<string, string> for flexible key addition across all pages
type TranslationMap = Record<string, string>;
type Translations = Record<LanguageCode, TranslationMap>;

const en: TranslationMap = {
  // Sidebar nav
  'nav.dashboard': 'Dashboard', 'nav.workspaces': 'Workspaces', 'nav.connections': 'Connections',
  'nav.assessments': 'Assessments', 'nav.migrations': 'Migrations', 'nav.jobs': 'Jobs',
  'nav.converter': 'Code Converter', 'nav.validations': 'Data Validation', 'nav.monitoring': 'Monitoring',
  'nav.admin': 'Admin',
  'nav.schemaAnalysis': 'Schema Analysis', 'nav.compatibilityCheck': 'Analyze', 'nav.analyze': 'Analyze',
  'nav.assessmentReports': 'Assessment Reports', 'nav.dataProfiling': 'Data Profiling',
  'nav.running': 'Running', 'nav.queued': 'Queued', 'nav.history': 'History',
  'nav.quickConvert': 'Quick Convert', 'nav.batch': 'Batch',
  'nav.queryHistory': 'Query History', 'nav.copyHistory': 'Copy History',
  'nav.taskHistory': 'Task History', 'nav.dynamicTables': 'Dynamic Tables', 'nav.governance': 'Governance',
  // Sidebar footer
  'sidebar.darkMode': 'Dark mode', 'sidebar.lightMode': 'Light mode', 'sidebar.language': 'Language',
  'sidebar.myProfile': 'My profile', 'sidebar.support': 'Support', 'sidebar.documentation': 'Documentation',
  'sidebar.privacyNotice': 'Privacy notice', 'sidebar.signOut': 'Sign Out',
  // Dashboard
  'dashboard.title': 'Dashboard', 'dashboard.subtitle': 'Overview of your migration platform',
  'dashboard.loading': 'Loading dashboard...', 'dashboard.loadFailed': 'Failed to load dashboard data.',
  'dashboard.connections': 'Connections', 'dashboard.assessments': 'Assessments',
  'dashboard.migrations': 'Migrations', 'dashboard.codeConversions': 'Code Conversions',
  'dashboard.connected': 'Connected', 'dashboard.done': 'Done', 'dashboard.running': 'Running',
  'dashboard.failed': 'Failed', 'dashboard.scheduled': 'Scheduled', 'dashboard.batches': 'Batches',
  'dashboard.src': 'Src', 'dashboard.tgt': 'Tgt',
  'dashboard.assessmentDiscovery': 'Assessment Discovery', 'dashboard.viewAll': 'View All',
  'dashboard.tables': 'Tables', 'dashboard.views': 'Views', 'dashboard.routines': 'Routines',
  'dashboard.totalDataVolume': 'Total data volume',
  'dashboard.migrationStatus': 'Migration Status',
  'dashboard.completed': 'Completed', 'dashboard.scheduled2': 'Scheduled',
  'dashboard.recentActivity': 'Recent Activity',
  'dashboard.copyHistory': 'Copy History', 'dashboard.noRecentActivity': 'No recent activity',
  'dashboard.name': 'Name', 'dashboard.status': 'Status', 'dashboard.size': 'Size',
  'dashboard.started': 'Started', 'dashboard.pathway': 'Pathway', 'dashboard.created': 'Created',
  'dashboard.table': 'Table', 'dashboard.rows': 'Rows',
  // Connections page
  'connections.title': 'Data Connections', 'connections.count': 'Connections',
  'connections.search': 'Search', 'connections.new': '+ New',
  'connections.sourceConnection': 'Source Connection', 'connections.targetConnection': 'Target Connection',
  'connections.loading': 'Loading connections...', 'connections.retry': 'Retry',
  'connections.noConnections': 'No connections found',
  'connections.createFirst': 'Create Your First Connection',
  'connections.name': 'NAME', 'connections.type': 'TYPE', 'connections.database': 'DATABASE',
  'connections.createdBy': 'CREATED BY', 'connections.connectionStatus': 'CONNECTION STATUS',
  'connections.lastTestedAt': 'LAST TESTED AT',
  'connections.testConnection': 'Test Connection', 'connections.updateConnection': 'Update Connection',
  'connections.deleteConnection': 'Delete Connection',
  'connections.deleteConfirmTitle': 'Delete Connection',
  'connections.deleteConfirmMsg': 'Are you sure you want to delete this connection? This action cannot be undone.',
  'connections.cancel': 'Cancel',
  'connections.connectionSuccessful': 'Connection Successful', 'connections.connectionFailed': 'Connection Failed',
  'connections.message': 'Message', 'connections.details': 'Details',
  'connections.troubleshooting': 'Troubleshooting Tips',
  'connections.close': 'Close',
  'connections.showing': 'Showing', 'connections.of': 'of',
  'connections.rowsPerPage': 'Rows per page:',
  'connections.connected': 'Connected', 'connections.disconnected': 'Disconnected', 'connections.testing': 'Testing',
  // Assessments page
  'assessments.title': 'Assessments', 'assessments.new': '+ New', 'assessments.search': 'Search assessments',
  'assessments.name': 'NAME', 'assessments.status': 'STATUS', 'assessments.datasets': 'DATASETS',
  'assessments.tables': 'TABLES', 'assessments.totalSize': 'TOTAL SIZE',
  'assessments.startedAt': 'STARTED AT', 'assessments.completedAt': 'COMPLETED AT',
  'assessments.run': 'Run Assessment', 'assessments.viewLogs': 'View Logs',
  'assessments.viewReport': 'View Report', 'assessments.downloadReport': 'Download Report',
  'assessments.edit': 'Edit Assessment', 'assessments.delete': 'Delete Assessment',
  'assessments.deleteConfirm': 'Delete Assessment',
  'assessments.deleteConfirmMsg': 'Are you sure you want to delete this assessment? This action cannot be undone.',
  'assessments.cancel': 'Cancel', 'assessments.noAssessments': 'No assessments yet',
  'assessments.noAssessmentsDesc': 'Create your first BigQuery assessment to analyze your data',
  'assessments.createFirst': 'Create Your First Assessment', 'assessments.loading': 'Loading assessments...',
  'assessments.started': 'Assessment started', 'assessments.completed': 'Completed',
  'assessments.failed': 'Failed', 'assessments.pending': 'Pending',
  'assessments.rowsPerPage': 'Rows per page:', 'assessments.showing': 'Showing',
  'common.of': 'of', 'common.retry': 'Retry',
  // Migrations page
  'migrations.title': 'Data Migrations', 'migrations.count': 'Migrations',
  'migrations.search': 'Search', 'migrations.new': '+ New', 'migrations.create': 'Create',
  'migrations.loading': 'Loading migrations...', 'migrations.noMigrations': 'No migrations found',
  'migrations.createFirst': 'Create Your First Migration',
  'migrations.name': 'NAME', 'migrations.source': 'SOURCE', 'migrations.destination': 'DESTINATION',
  'migrations.createdBy': 'CREATED BY', 'migrations.status': 'STATUS', 'migrations.lastRunAt': 'LAST RUN AT',
  'migrations.runMigration': 'Run Migration', 'migrations.cancelMigration': 'Cancel Migration',
  'migrations.viewLogs': 'View Logs', 'migrations.editMigration': 'Edit Migration',
  'migrations.deleteMigration': 'Delete Migration',
  'migrations.deleteConfirmTitle': 'Delete Migration',
  'migrations.deleteConfirmMsg': 'Are you sure you want to delete this migration? This action cannot be undone and will stop any running migration processes.',
  'migrations.cancel': 'Cancel',
  'migrations.restartTitle': 'Restart Migration',
  'migrations.restartMsg': 'Restart from the beginning? This will clear all progress and start fresh. Existing data from previous runs will be preserved.',
  'migrations.restartBtn': 'Restart Migration',
  'migrations.cancelTitle': 'Cancel Migration',
  'migrations.cancelMsg': 'This will stop the migration process. You can resume it later if needed.',
  'migrations.keepRunning': 'Keep Running',
  'migrations.updateTitle': 'Update Migration', 'migrations.migrationName': 'Migration Name',
  'migrations.saveChanges': 'Save Changes',
  'migrations.showing': 'Showing', 'migrations.of': 'of', 'migrations.rowsPerPage': 'Rows per page:',
  'migrations.migrationLogs': 'Migration Logs', 'migrations.loadingLogs': 'Loading logs...',
  'migrations.failedToLoadLogs': 'Failed to Load Logs', 'migrations.migration': 'Migration',
  'migrations.success': 'Success', 'migrations.ready': 'Ready', 'migrations.paused': 'Paused',
  'migrations.cancelled': 'Cancelled',
  // Jobs page
  'jobs.title': 'Jobs', 'jobs.subtitle': 'Background tasks and operations',
  'jobs.loading': 'Loading jobs...', 'jobs.noJobs': 'No jobs found',
  'jobs.all': 'All', 'jobs.running': 'Running', 'jobs.completed': 'Completed',
  'jobs.failed': 'Failed', 'jobs.pending': 'Pending',
  'jobs.name': 'NAME', 'jobs.type': 'TYPE', 'jobs.status': 'STATUS',
  'jobs.progress': 'PROGRESS', 'jobs.startedAt': 'STARTED AT', 'jobs.duration': 'DURATION',
  'jobs.search': 'Search jobs',
  // Validation page
  'validation.title': 'Data Validation', 'validation.loading': 'Loading...',
  'validation.createValidation': 'Create Validation', 'validation.noRuns': 'No validation runs found',
  'validation.all': 'All', 'validation.pending': 'Pending', 'validation.running': 'Running',
  'validation.completed': 'Completed', 'validation.failed': 'Failed',
  'validation.rowsPerPage': 'Rows per page:', 'validation.showing': 'Showing',
  // Common
  'common.search': 'Search', 'common.cancel': 'Cancel', 'common.close': 'Close',
  'common.delete': 'Delete', 'common.edit': 'Edit', 'common.save': 'Save',
  'common.loading': 'Loading...', 'common.noData': 'No data',
  'common.showing': 'Showing', 'common.rowsPerPage': 'Rows per page:',
  'common.never': 'Never', 'common.justNow': 'Just now',
  // Profile page
  'profile.title': 'My Profile', 'profile.subtitle': 'Manage your account settings and preferences',
  'profile.userInfo': 'User Information', 'profile.username': 'Username', 'profile.role': 'Role',
  'profile.theme': 'Theme', 'profile.language': 'Language', 'profile.preferences': 'Preferences',
  'profile.selectLanguage': 'Select Language', 'profile.changePassword': 'Change Password',
  'profile.currentPassword': 'Current Password', 'profile.newPassword': 'New Password',
  'profile.confirmPassword': 'Confirm Password', 'profile.updatePassword': 'Update Password',
  'profile.passwordMismatch': 'Passwords do not match', 'profile.passwordTooShort': 'Password must be at least 6 characters',
  'profile.passwordChanged': 'Password updated successfully',
  'profile.activity': 'Activity Overview',
  // Admin
  'admin.settingsDesc': 'Administration settings (Admin only)',
  'admin.targets': 'Targets', 'admin.targetsDesc': 'Target database connections management',
  'admin.awsAccounts': 'AWS Accounts', 'admin.awsAccountsDesc': 'AWS Accounts management interface',
  'admin.users': 'Users', 'admin.usersDesc': 'Users management interface',
  'admin.dataConnections': 'Data Connections', 'admin.sources': 'Sources',
  // Validation extra
  'validation.subtitle': 'Post-migration data integrity verification',
  // Converter page
  'converter.title': 'Code Converter', 'converter.subtitle': 'Convert SQL and database code between dialects',
  'converter.sourceDialect': 'Source Dialect', 'converter.targetDialect': 'Target Dialect',
  'converter.assetType': 'Asset Type', 'converter.assetName': 'Asset Name',
  'converter.bedrockModel': 'Bedrock Model', 'converter.promptTemplate': 'Prompt Template',
  'converter.localFiles': 'Local Files', 'converter.maxRetries': 'Max Retries',
  'converter.sourceCode': 'Source Code', 'converter.convertedCode': 'Converted Code',
  'converter.convert': 'Convert', 'converter.converting': 'Converting…',
  'converter.pastePlaceholder': 'Paste your SQL or database code here…',
  'converter.conversionHistory': 'Conversion History',
  'converter.sourceConnection': 'Source Connection', 'converter.targetConnection': 'Target Connection',
  // Copy History
  'copyHistory.title': 'Copy History', 'copyHistory.searchPlaceholder': 'Search by migration or table...',
  'copyHistory.allStatus': 'All Status', 'copyHistory.completed': 'Completed',
  'copyHistory.running': 'Running', 'copyHistory.failed': 'Failed',
  'copyHistory.loading': 'Loading copy history...', 'copyHistory.noRecords': 'No COPY Records Found',
  'copyHistory.noRecordsDesc': 'COPY commands will appear here when migrations are executed.',
  'copyHistory.migration': 'Migration', 'copyHistory.table': 'Table', 'copyHistory.status': 'Status',
  'copyHistory.rows': 'Rows', 'copyHistory.size': 'Size', 'copyHistory.duration': 'Duration',
  'copyHistory.startedAt': 'Started At', 'copyHistory.format': 'Format',
  'copyHistory.details': 'COPY Command Details', 'copyHistory.started': 'Started',
  'copyHistory.completed2': 'Completed', 'copyHistory.rowsLoaded': 'Rows Loaded',
  'copyHistory.bytesLoaded': 'Bytes Loaded', 'copyHistory.compression': 'Compression',
  'copyHistory.sourceUri': 'Source URI', 'copyHistory.copyCommand': 'COPY Command',
  'copyHistory.error': 'Error', 'copyHistory.errorDetails': 'Error Details',
  'copyHistory.showing': 'Showing', 'copyHistory.of': 'of',
  'copyHistory.rowsPerPage': 'Rows per page:', 'copyHistory.page': 'Page',
  // Task History
  'taskHistory.title': 'Task History', 'taskHistory.searchPlaceholder': 'Search by migration, table, or ARN...',
  'taskHistory.allStatus': 'All Status', 'taskHistory.completed': 'Completed',
  'taskHistory.running': 'Running', 'taskHistory.failed': 'Failed', 'taskHistory.agentOffline': 'Agent Offline',
  'taskHistory.loading': 'Loading task history...', 'taskHistory.noRecords': 'No DataSync Tasks Found',
  'taskHistory.noRecordsDesc': 'DataSync tasks will appear here when migrations are executed via Path B.',
  'taskHistory.migration': 'Migration', 'taskHistory.table': 'Table', 'taskHistory.status': 'Status',
  'taskHistory.files': 'Files', 'taskHistory.size': 'Size', 'taskHistory.duration': 'Duration',
  'taskHistory.agentIp': 'Agent IP', 'taskHistory.startedAt': 'Started At',
  'taskHistory.details': 'DataSync Task Details', 'taskHistory.taskType': 'Task Type',
  'taskHistory.started': 'Started', 'taskHistory.completed2': 'Completed',
  'taskHistory.filesTransferred': 'Files Transferred', 'taskHistory.bytesTransferred': 'Bytes Transferred',
  'taskHistory.source': 'Source', 'taskHistory.destination': 'Destination',
  'taskHistory.taskArn': 'Task ARN', 'taskHistory.executionArn': 'Execution ARN',
  'taskHistory.agentArn': 'Agent ARN', 'taskHistory.error': 'Error', 'taskHistory.errorDetails': 'Error Details',
  'taskHistory.showing': 'Showing', 'taskHistory.of': 'of',
  'taskHistory.rowsPerPage': 'Rows per page:', 'taskHistory.page': 'Page',
  // Validation extra
  'validation.passed': 'Passed', 'validation.active': 'Active',
  'validation.newValidation': 'New Validation', 'validation.createStart': 'Create & Start',
  'validation.newRun': 'New Validation Run', 'validation.migration': 'Migration',
  'validation.selectMigration': 'Select a migration', 'validation.tables': 'Tables',
  'validation.selectTables': 'Select tables...', 'validation.allTablesSelected': 'All tables selected',
  'validation.selectAll': 'Select All', 'validation.checksPerTable': 'Validation Checks per Table',
  'validation.totalRows': 'Total Rows', 'validation.recordsToValidate': 'Records to Validate',
  'validation.bedrockModel': 'Bedrock Model (optional)', 'validation.noneSkipAi': 'None (skip AI analysis)',
  'validation.loadingModels': 'Loading models...', 'validation.loadingMigration': 'Loading migration details...',
  'validation.creating': 'Creating…', 'validation.deleteConfirm': 'Delete this validation run? This cannot be undone.',
  'validation.noRunsDesc': 'No validation runs found. Click "New Validation" to get started.',
  'validation.id': 'ID', 'validation.progress': 'Progress', 'validation.started': 'Started',
  'validation.duration': 'Duration', 'validation.actions': 'Actions',
  // Workspaces
  'workspaces.title': 'Your Workspaces', 'workspaces.createWorkspace': 'Create Workspace',
  'workspaces.pinned': 'Pinned', 'workspaces.noPinned': 'No pinned workspaces',
  'workspaces.searchPlaceholder': 'Search workspaces', 'workspaces.selectPrompt': 'Select a workspace to view analysis',
  'workspaces.reAnalyze': 'Re-analyze', 'workspaces.overview': 'Overview',
  'workspaces.sourceConnections': 'Source Connections', 'workspaces.targetConnections': 'Target Connections',
  'workspaces.compatibilityCheck': 'Compatibility Check', 'workspaces.codeConverter': 'Code Converter',
  'workspaces.migrationJobs': 'Migration Jobs', 'workspaces.loading': 'Loading workspaces...',
  'workspaces.loadingAnalysis': 'Loading analysis...', 'workspaces.noAnalysis': 'No analysis data available. Click Re-analyze to start.',
  'workspaces.name': 'Name', 'workspaces.description': 'Description (optional)',
  'workspaces.creating': 'Creating...', 'workspaces.create': 'Create',
  'workspaces.sourceType': 'SOURCE TYPE', 'workspaces.targetType': 'TARGET TYPE',
  'workspaces.datasets': 'DATASETS', 'workspaces.tables': 'TABLES', 'workspaces.totalRecords': 'TOTAL RECORDS',
  'workspaces.topTables': 'Top Tables by Row Count', 'workspaces.noTableData': 'No table data available. Run an assessment to populate.',
  'workspaces.noAssessments': 'No assessments found in this workspace.',
  'workspaces.noMigrations': 'No migrations found in this workspace.',
  'workspaces.noSourceConns': 'No source connections', 'workspaces.noTargetConns': 'No target connections',
  'workspaces.total': 'Total', 'workspaces.completed': 'Completed', 'workspaces.running': 'Running', 'workspaces.failed': 'Failed',
  'workspaces.migrationName': 'Migration Name', 'workspaces.pathway': 'Pathway',
  'workspaces.stage': 'Stage', 'workspaces.progress': 'Progress', 'workspaces.sourceTarget': 'Source → Target',
  'workspaces.duration': 'Duration', 'workspaces.created': 'Created',
  // Query History
  'queryHistory.subtitle': 'Historical log of all queries executed against databases',
  'queryHistory.searchPlaceholder': 'Search queries...', 'queryHistory.allStatus': 'All Status',
  'queryHistory.success': 'Success', 'queryHistory.failed': 'Failed',
  'queryHistory.allDatabases': 'All Databases', 'queryHistory.loading': 'Loading query history...',
  'queryHistory.noRecords': 'No Query Records Found',
  'queryHistory.noRecordsDesc': 'Query records will appear here when queries are executed against your databases.',
  'queryHistory.query': 'Query', 'queryHistory.database': 'Database', 'queryHistory.connection': 'Connection',
  'queryHistory.status': 'Status', 'queryHistory.duration': 'Duration', 'queryHistory.rows': 'Rows',
  'queryHistory.executedBy': 'Executed By', 'queryHistory.executedAt': 'Executed At',
  'queryHistory.queryDetails': 'Query Details', 'queryHistory.error': 'Error',
  // Dynamic Tables
  'dynamicTables.subtitle': 'Monitor dynamically created tables during migration',
  'dynamicTables.searchPlaceholder': 'Search tables...', 'dynamicTables.loading': 'Loading dynamic tables...',
  'dynamicTables.noTables': 'No Dynamic Tables Found',
  'dynamicTables.noTablesDesc': 'Dynamic tables will appear here when migrations create staging or temporary tables.',
  'dynamicTables.tableName': 'Table Name', 'dynamicTables.schema': 'Schema',
  'dynamicTables.sourceTable': 'Source Table', 'dynamicTables.migration': 'Migration',
  'dynamicTables.rows': 'Rows', 'dynamicTables.size': 'Size',
  'dynamicTables.status': 'Status', 'dynamicTables.createdAt': 'Created At',
  // Governance
  'governance.subtitle': 'Audit trail of platform actions for compliance',
  'governance.searchPlaceholder': 'Search audit logs...', 'governance.allActions': 'All Actions',
  'governance.create': 'Create', 'governance.update': 'Update', 'governance.delete': 'Delete',
  'governance.execute': 'Execute', 'governance.login': 'Login',
  'governance.loading': 'Loading audit logs...', 'governance.noRecords': 'No Audit Records Found',
  'governance.noRecordsDesc': 'Audit records will appear here as platform actions are performed.',
  'governance.action': 'Action', 'governance.resource': 'Resource', 'governance.resourceName': 'Resource Name',
  'governance.performedBy': 'Performed By', 'governance.status': 'Status',
  'governance.ipAddress': 'IP Address', 'governance.timestamp': 'Timestamp',
  'governance.auditDetails': 'Audit Details', 'governance.details': 'Details',
};

const ko: TranslationMap = {
  // Sidebar nav
  'nav.dashboard': '대시보드', 'nav.workspaces': '워크스페이스', 'nav.connections': '연결',
  'nav.assessments': '평가', 'nav.migrations': '마이그레이션', 'nav.jobs': '작업',
  'nav.converter': '코드 변환기', 'nav.validations': '데이터 검증', 'nav.monitoring': '모니터링',
  'nav.admin': '관리자',
  'nav.schemaAnalysis': '스키마 분석', 'nav.compatibilityCheck': '호환성 검사',
  'nav.assessmentReports': '평가 보고서', 'nav.dataProfiling': '데이터 프로파일링',
  'nav.running': '실행 중', 'nav.queued': '대기 중', 'nav.history': '기록',
  'nav.quickConvert': '빠른 변환', 'nav.batch': '일괄 처리',
  'nav.queryHistory': '쿼리 기록', 'nav.copyHistory': '복사 기록',
  'nav.taskHistory': '작업 기록', 'nav.dynamicTables': '동적 테이블', 'nav.governance': '거버넌스',
  'sidebar.darkMode': '다크 모드', 'sidebar.lightMode': '라이트 모드', 'sidebar.language': '언어',
  'sidebar.myProfile': '내 프로필', 'sidebar.support': '지원', 'sidebar.documentation': '문서',
  'sidebar.privacyNotice': '개인정보 보호', 'sidebar.signOut': '로그아웃',
  // Dashboard
  'dashboard.title': '대시보드', 'dashboard.subtitle': '마이그레이션 플랫폼 개요',
  'dashboard.loading': '대시보드 로딩 중...', 'dashboard.loadFailed': '대시보드 데이터를 불러오지 못했습니다.',
  'dashboard.connections': '연결', 'dashboard.assessments': '평가',
  'dashboard.migrations': '마이그레이션', 'dashboard.codeConversions': '코드 변환',
  'dashboard.connected': '연결됨', 'dashboard.done': '완료', 'dashboard.running': '실행 중',
  'dashboard.failed': '실패', 'dashboard.scheduled': '예약됨', 'dashboard.batches': '배치',
  'dashboard.src': '소스', 'dashboard.tgt': '대상',
  'dashboard.assessmentDiscovery': '평가 검색', 'dashboard.viewAll': '전체 보기',
  'dashboard.tables': '테이블', 'dashboard.views': '뷰', 'dashboard.routines': '루틴',
  'dashboard.totalDataVolume': '총 데이터 볼륨',
  'dashboard.migrationStatus': '마이그레이션 상태',
  'dashboard.completed': '완료됨', 'dashboard.scheduled2': '예약됨',
  'dashboard.recentActivity': '최근 활동',
  'dashboard.copyHistory': '복사 기록', 'dashboard.noRecentActivity': '최근 활동 없음',
  'dashboard.name': '이름', 'dashboard.status': '상태', 'dashboard.size': '크기',
  'dashboard.started': '시작', 'dashboard.pathway': '경로', 'dashboard.created': '생성',
  'dashboard.table': '테이블', 'dashboard.rows': '행',
  // Connections
  'connections.title': '데이터 연결', 'connections.count': '연결',
  'connections.search': '검색', 'connections.new': '+ 새로 만들기',
  'connections.sourceConnection': '소스 연결', 'connections.targetConnection': '대상 연결',
  'connections.loading': '연결 로딩 중...', 'connections.retry': '재시도',
  'connections.noConnections': '연결이 없습니다',
  'connections.createFirst': '첫 번째 연결 만들기',
  'connections.name': '이름', 'connections.type': '유형', 'connections.database': '데이터베이스',
  'connections.createdBy': '생성자', 'connections.connectionStatus': '연결 상태',
  'connections.lastTestedAt': '마지막 테스트',
  'connections.testConnection': '연결 테스트', 'connections.updateConnection': '연결 수정',
  'connections.deleteConnection': '연결 삭제',
  'connections.deleteConfirmTitle': '연결 삭제',
  'connections.deleteConfirmMsg': '이 연결을 삭제하시겠습니까? 이 작업은 취소할 수 없습니다.',
  'connections.cancel': '취소',
  'connections.connectionSuccessful': '연결 성공', 'connections.connectionFailed': '연결 실패',
  'connections.message': '메시지', 'connections.details': '세부 정보',
  'connections.troubleshooting': '문제 해결 팁',
  'connections.close': '닫기',
  'connections.showing': '표시 중', 'connections.of': '/',
  'connections.rowsPerPage': '페이지당 행:',
  'connections.connected': '연결됨', 'connections.disconnected': '연결 끊김', 'connections.testing': '테스트 중',
  // Assessments
  'assessments.title': '평가', 'assessments.new': '+ 새로 만들기', 'assessments.search': '평가 검색',
  'assessments.name': '이름', 'assessments.status': '상태', 'assessments.datasets': '데이터셋',
  'assessments.tables': '테이블', 'assessments.totalSize': '전체 크기',
  'assessments.startedAt': '시작 시간', 'assessments.completedAt': '완료 시간',
  'assessments.run': '평가 실행', 'assessments.viewLogs': '로그 보기',
  'assessments.viewReport': '보고서 보기', 'assessments.downloadReport': '보고서 다운로드',
  'assessments.edit': '평가 편집', 'assessments.delete': '평가 삭제',
  'assessments.deleteConfirm': '평가 삭제',
  'assessments.deleteConfirmMsg': '이 평가를 삭제하시겠습니까? 이 작업은 취소할 수 없습니다.',
  'assessments.cancel': '취소', 'assessments.noAssessments': '아직 평가가 없습니다',
  'assessments.noAssessmentsDesc': '첫 번째 BigQuery 평가를 만들어 데이터를 분석하세요',
  'assessments.createFirst': '첫 번째 평가 만들기', 'assessments.loading': '평가 로딩 중...',
  'assessments.started': '평가 시작됨', 'assessments.completed': '완료됨',
  'assessments.failed': '실패', 'assessments.pending': '대기 중',
  'assessments.rowsPerPage': '페이지당 행:', 'assessments.showing': '표시 중',
  'common.of': '/', 'common.retry': '재시도',
  // Migrations
  'migrations.title': '데이터 마이그레이션', 'migrations.count': '마이그레이션',
  'migrations.search': '검색', 'migrations.new': '+ 새로 만들기', 'migrations.create': '생성',
  'migrations.loading': '마이그레이션 로딩 중...', 'migrations.noMigrations': '마이그레이션이 없습니다',
  'migrations.createFirst': '첫 번째 마이그레이션 만들기',
  'migrations.name': '이름', 'migrations.source': '소스', 'migrations.destination': '대상',
  'migrations.createdBy': '생성자', 'migrations.status': '상태', 'migrations.lastRunAt': '마지막 실행',
  'migrations.runMigration': '마이그레이션 실행', 'migrations.cancelMigration': '마이그레이션 취소',
  'migrations.viewLogs': '로그 보기', 'migrations.editMigration': '마이그레이션 편집',
  'migrations.deleteMigration': '마이그레이션 삭제',
  'migrations.deleteConfirmTitle': '마이그레이션 삭제',
  'migrations.deleteConfirmMsg': '이 마이그레이션을 삭제하시겠습니까? 이 작업은 취소할 수 없으며 실행 중인 프로세스가 중지됩니다.',
  'migrations.cancel': '취소',
  'migrations.restartTitle': '마이그레이션 재시작',
  'migrations.restartMsg': '처음부터 다시 시작하시겠습니까? 모든 진행 상황이 초기화됩니다. 이전 실행 데이터는 보존됩니다.',
  'migrations.restartBtn': '마이그레이션 재시작',
  'migrations.cancelTitle': '마이그레이션 취소',
  'migrations.cancelMsg': '마이그레이션 프로세스가 중지됩니다. 나중에 다시 시작할 수 있습니다.',
  'migrations.keepRunning': '계속 실행',
  'migrations.updateTitle': '마이그레이션 수정', 'migrations.migrationName': '마이그레이션 이름',
  'migrations.saveChanges': '변경 사항 저장',
  'migrations.showing': '표시 중', 'migrations.of': '/', 'migrations.rowsPerPage': '페이지당 행:',
  'migrations.migrationLogs': '마이그레이션 로그', 'migrations.loadingLogs': '로그 로딩 중...',
  'migrations.failedToLoadLogs': '로그 로드 실패', 'migrations.migration': '마이그레이션',
  'migrations.success': '성공', 'migrations.ready': '준비됨', 'migrations.paused': '일시 중지',
  'migrations.cancelled': '취소됨',
  // Jobs
  'jobs.title': '작업', 'jobs.subtitle': '백그라운드 작업 및 운영',
  'jobs.loading': '작업 로딩 중...', 'jobs.noJobs': '작업이 없습니다',
  'jobs.all': '전체', 'jobs.running': '실행 중', 'jobs.completed': '완료됨',
  'jobs.failed': '실패', 'jobs.pending': '대기 중',
  'jobs.name': '이름', 'jobs.type': '유형', 'jobs.status': '상태',
  'jobs.progress': '진행률', 'jobs.startedAt': '시작 시간', 'jobs.duration': '소요 시간',
  'jobs.search': '작업 검색',
  // Validation
  'validation.title': '데이터 검증', 'validation.loading': '로딩 중...',
  'validation.createValidation': '검증 생성', 'validation.noRuns': '검증 실행이 없습니다',
  'validation.all': '전체', 'validation.pending': '대기 중', 'validation.running': '실행 중',
  'validation.completed': '완료됨', 'validation.failed': '실패',
  'validation.rowsPerPage': '페이지당 행:', 'validation.showing': '표시 중',
  // Common
  'common.search': '검색', 'common.cancel': '취소', 'common.close': '닫기',
  'common.delete': '삭제', 'common.edit': '편집', 'common.save': '저장',
  'common.loading': '로딩 중...', 'common.noData': '데이터 없음',
  'common.showing': '표시 중', 'common.rowsPerPage': '페이지당 행:',
  'common.never': '없음', 'common.justNow': '방금 전',
  // Profile
  'profile.title': '내 프로필', 'profile.subtitle': '계정 설정 및 환경설정 관리',
  'profile.userInfo': '사용자 정보', 'profile.username': '사용자 이름', 'profile.role': '역할',
  'profile.theme': '테마', 'profile.language': '언어', 'profile.preferences': '환경설정',
  'profile.selectLanguage': '언어 선택', 'profile.changePassword': '비밀번호 변경',
  'profile.currentPassword': '현재 비밀번호', 'profile.newPassword': '새 비밀번호',
  'profile.confirmPassword': '비밀번호 확인', 'profile.updatePassword': '비밀번호 업데이트',
  'profile.passwordMismatch': '비밀번호가 일치하지 않습니다', 'profile.passwordTooShort': '비밀번호는 6자 이상이어야 합니다',
  'profile.passwordChanged': '비밀번호가 성공적으로 변경되었습니다',
  'profile.activity': '활동 개요',
  'admin.settingsDesc': '관리 설정 (관리자 전용)',
  'admin.targets': '대상', 'admin.targetsDesc': '대상 데이터베이스 연결 관리',
  'admin.awsAccounts': 'AWS 계정', 'admin.awsAccountsDesc': 'AWS 계정 관리 인터페이스',
  'admin.users': '사용자', 'admin.usersDesc': '사용자 관리 인터페이스',
  'admin.dataConnections': '데이터 연결', 'admin.sources': '소스',
  'validation.subtitle': '마이그레이션 후 데이터 무결성 검증',
  // Converter
  'converter.title': '코드 변환기', 'converter.subtitle': 'SQL 및 데이터베이스 코드를 다른 방언으로 변환',
  'converter.sourceDialect': '소스 방언', 'converter.targetDialect': '대상 방언',
  'converter.assetType': '자산 유형', 'converter.assetName': '자산 이름',
  'converter.bedrockModel': 'Bedrock 모델', 'converter.promptTemplate': '프롬프트 템플릿',
  'converter.localFiles': '로컬 파일', 'converter.maxRetries': '최대 재시도',
  'converter.sourceCode': '소스 코드', 'converter.convertedCode': '변환된 코드',
  'converter.convert': '변환', 'converter.converting': '변환 중…',
  'converter.pastePlaceholder': 'SQL 또는 데이터베이스 코드를 여기에 붙여넣으세요…',
  'converter.conversionHistory': '변환 기록',
  'converter.sourceConnection': '소스 연결', 'converter.targetConnection': '대상 연결',
  // Copy History
  'copyHistory.title': '복사 기록', 'copyHistory.searchPlaceholder': '마이그레이션 또는 테이블 검색...',
  'copyHistory.allStatus': '전체 상태', 'copyHistory.completed': '완료됨',
  'copyHistory.running': '실행 중', 'copyHistory.failed': '실패',
  'copyHistory.loading': '복사 기록 로딩 중...', 'copyHistory.noRecords': 'COPY 기록 없음',
  'copyHistory.noRecordsDesc': '마이그레이션 실행 시 COPY 명령이 여기에 표시됩니다.',
  'copyHistory.migration': '마이그레이션', 'copyHistory.table': '테이블', 'copyHistory.status': '상태',
  'copyHistory.rows': '행', 'copyHistory.size': '크기', 'copyHistory.duration': '소요 시간',
  'copyHistory.startedAt': '시작 시간', 'copyHistory.format': '형식',
  'copyHistory.details': 'COPY 명령 세부 정보', 'copyHistory.started': '시작',
  'copyHistory.completed2': '완료', 'copyHistory.rowsLoaded': '로드된 행',
  'copyHistory.bytesLoaded': '로드된 바이트', 'copyHistory.compression': '압축',
  'copyHistory.sourceUri': '소스 URI', 'copyHistory.copyCommand': 'COPY 명령',
  'copyHistory.error': '오류', 'copyHistory.errorDetails': '오류 세부 정보',
  'copyHistory.showing': '표시 중', 'copyHistory.of': '/',
  'copyHistory.rowsPerPage': '페이지당 행:', 'copyHistory.page': '페이지',
  // Task History
  'taskHistory.title': '작업 기록', 'taskHistory.searchPlaceholder': '마이그레이션, 테이블 또는 ARN 검색...',
  'taskHistory.allStatus': '전체 상태', 'taskHistory.completed': '완료됨',
  'taskHistory.running': '실행 중', 'taskHistory.failed': '실패', 'taskHistory.agentOffline': '에이전트 오프라인',
  'taskHistory.loading': '작업 기록 로딩 중...', 'taskHistory.noRecords': 'DataSync 작업 없음',
  'taskHistory.noRecordsDesc': 'Path B를 통해 마이그레이션 실행 시 DataSync 작업이 여기에 표시됩니다.',
  'taskHistory.migration': '마이그레이션', 'taskHistory.table': '테이블', 'taskHistory.status': '상태',
  'taskHistory.files': '파일', 'taskHistory.size': '크기', 'taskHistory.duration': '소요 시간',
  'taskHistory.agentIp': '에이전트 IP', 'taskHistory.startedAt': '시작 시간',
  'taskHistory.details': 'DataSync 작업 세부 정보', 'taskHistory.taskType': '작업 유형',
  'taskHistory.started': '시작', 'taskHistory.completed2': '완료',
  'taskHistory.filesTransferred': '전송된 파일', 'taskHistory.bytesTransferred': '전송된 바이트',
  'taskHistory.source': '소스', 'taskHistory.destination': '대상',
  'taskHistory.taskArn': '작업 ARN', 'taskHistory.executionArn': '실행 ARN',
  'taskHistory.agentArn': '에이전트 ARN', 'taskHistory.error': '오류', 'taskHistory.errorDetails': '오류 세부 정보',
  'taskHistory.showing': '표시 중', 'taskHistory.of': '/',
  'taskHistory.rowsPerPage': '페이지당 행:', 'taskHistory.page': '페이지',
  // Validation extra
  'validation.passed': '통과', 'validation.active': '활성',
  'validation.newValidation': '새 검증', 'validation.createStart': '생성 및 시작',
  'validation.newRun': '새 검증 실행', 'validation.migration': '마이그레이션',
  'validation.selectMigration': '마이그레이션 선택', 'validation.tables': '테이블',
  'validation.selectTables': '테이블 선택...', 'validation.allTablesSelected': '모든 테이블 선택됨',
  'validation.selectAll': '전체 선택', 'validation.checksPerTable': '테이블별 검증 항목',
  'validation.totalRows': '전체 행', 'validation.recordsToValidate': '검증할 레코드',
  'validation.bedrockModel': 'Bedrock 모델 (선택사항)', 'validation.noneSkipAi': '없음 (AI 분석 건너뛰기)',
  'validation.loadingModels': '모델 로딩 중...', 'validation.loadingMigration': '마이그레이션 세부 정보 로딩 중...',
  'validation.creating': '생성 중…', 'validation.deleteConfirm': '이 검증 실행을 삭제하시겠습니까? 취소할 수 없습니다.',
  'validation.noRunsDesc': '검증 실행이 없습니다. "새 검증"을 클릭하여 시작하세요.',
  'validation.id': 'ID', 'validation.progress': '진행률', 'validation.started': '시작',
  'validation.duration': '소요 시간', 'validation.actions': '작업',
  // Workspaces
  'workspaces.title': '워크스페이스', 'workspaces.createWorkspace': '워크스페이스 생성',
  'workspaces.pinned': '고정됨', 'workspaces.noPinned': '고정된 워크스페이스 없음',
  'workspaces.searchPlaceholder': '워크스페이스 검색', 'workspaces.selectPrompt': '분석을 보려면 워크스페이스를 선택하세요',
  'workspaces.reAnalyze': '재분석', 'workspaces.overview': '개요',
  'workspaces.sourceConnections': '소스 연결', 'workspaces.targetConnections': '대상 연결',
  'workspaces.compatibilityCheck': '호환성 검사', 'workspaces.codeConverter': '코드 변환기',
  'workspaces.migrationJobs': '마이그레이션 작업', 'workspaces.loading': '워크스페이스 로딩 중...',
  'workspaces.loadingAnalysis': '분석 로딩 중...', 'workspaces.noAnalysis': '분석 데이터가 없습니다. 재분석을 클릭하세요.',
  'workspaces.name': '이름', 'workspaces.description': '설명 (선택사항)',
  'workspaces.creating': '생성 중...', 'workspaces.create': '생성',
  'workspaces.sourceType': '소스 유형', 'workspaces.targetType': '대상 유형',
  'workspaces.datasets': '데이터셋', 'workspaces.tables': '테이블', 'workspaces.totalRecords': '전체 레코드',
  'workspaces.topTables': '행 수 기준 상위 테이블', 'workspaces.noTableData': '테이블 데이터가 없습니다. 평가를 실행하세요.',
  'workspaces.noAssessments': '이 워크스페이스에 평가가 없습니다.',
  'workspaces.noMigrations': '이 워크스페이스에 마이그레이션이 없습니다.',
  'workspaces.noSourceConns': '소스 연결 없음', 'workspaces.noTargetConns': '대상 연결 없음',
  'workspaces.total': '전체', 'workspaces.completed': '완료됨', 'workspaces.running': '실행 중', 'workspaces.failed': '실패',
  'workspaces.migrationName': '마이그레이션 이름', 'workspaces.pathway': '경로',
  'workspaces.stage': '단계', 'workspaces.progress': '진행률', 'workspaces.sourceTarget': '소스 → 대상',
  'workspaces.duration': '소요 시간', 'workspaces.created': '생성',
  // Query History
  'queryHistory.subtitle': '데이터베이스에 대해 실행된 모든 쿼리의 기록',
  'queryHistory.searchPlaceholder': '쿼리 검색...', 'queryHistory.allStatus': '전체 상태',
  'queryHistory.success': '성공', 'queryHistory.failed': '실패',
  'queryHistory.allDatabases': '전체 데이터베이스', 'queryHistory.loading': '쿼리 기록 로딩 중...',
  'queryHistory.noRecords': '쿼리 기록 없음',
  'queryHistory.noRecordsDesc': '데이터베이스에 쿼리가 실행되면 여기에 표시됩니다.',
  'queryHistory.query': '쿼리', 'queryHistory.database': '데이터베이스', 'queryHistory.connection': '연결',
  'queryHistory.status': '상태', 'queryHistory.duration': '소요 시간', 'queryHistory.rows': '행',
  'queryHistory.executedBy': '실행자', 'queryHistory.executedAt': '실행 시간',
  'queryHistory.queryDetails': '쿼리 세부 정보', 'queryHistory.error': '오류',
  // Dynamic Tables
  'dynamicTables.subtitle': '마이그레이션 중 동적으로 생성된 테이블 모니터링',
  'dynamicTables.searchPlaceholder': '테이블 검색...', 'dynamicTables.loading': '동적 테이블 로딩 중...',
  'dynamicTables.noTables': '동적 테이블 없음',
  'dynamicTables.noTablesDesc': '마이그레이션이 스테이징 또는 임시 테이블을 생성하면 여기에 표시됩니다.',
  'dynamicTables.tableName': '테이블 이름', 'dynamicTables.schema': '스키마',
  'dynamicTables.sourceTable': '소스 테이블', 'dynamicTables.migration': '마이그레이션',
  'dynamicTables.rows': '행', 'dynamicTables.size': '크기',
  'dynamicTables.status': '상태', 'dynamicTables.createdAt': '생성 시간',
  // Governance
  'governance.subtitle': '규정 준수를 위한 플랫폼 작업 감사 추적',
  'governance.searchPlaceholder': '감사 로그 검색...', 'governance.allActions': '전체 작업',
  'governance.create': '생성', 'governance.update': '수정', 'governance.delete': '삭제',
  'governance.execute': '실행', 'governance.login': '로그인',
  'governance.loading': '감사 로그 로딩 중...', 'governance.noRecords': '감사 기록 없음',
  'governance.noRecordsDesc': '플랫폼 작업이 수행되면 감사 기록이 여기에 표시됩니다.',
  'governance.action': '작업', 'governance.resource': '리소스', 'governance.resourceName': '리소스 이름',
  'governance.performedBy': '수행자', 'governance.status': '상태',
  'governance.ipAddress': 'IP 주소', 'governance.timestamp': '시간',
  'governance.auditDetails': '감사 세부 정보', 'governance.details': '세부 정보',
};

const zh: TranslationMap = {
  'nav.dashboard': '仪表板', 'nav.workspaces': '工作区', 'nav.connections': '连接',
  'nav.assessments': '评估', 'nav.migrations': '迁移', 'nav.jobs': '任务',
  'nav.converter': '代码转换器', 'nav.validations': '数据验证', 'nav.monitoring': '监控',
  'nav.admin': '管理', 'nav.schemaAnalysis': '架构分析', 'nav.compatibilityCheck': '兼容性检查',
  'nav.assessmentReports': '评估报告', 'nav.dataProfiling': '数据分析',
  'nav.running': '运行中', 'nav.queued': '排队中', 'nav.history': '历史',
  'nav.quickConvert': '快速转换', 'nav.batch': '批量处理',
  'nav.queryHistory': '查询历史', 'nav.copyHistory': '复制历史',
  'nav.taskHistory': '任务历史', 'nav.dynamicTables': '动态表', 'nav.governance': '治理',
  'sidebar.darkMode': '深色模式', 'sidebar.lightMode': '浅色模式', 'sidebar.language': '语言',
  'sidebar.myProfile': '我的资料', 'sidebar.support': '支持', 'sidebar.documentation': '文档',
  'sidebar.privacyNotice': '隐私声明', 'sidebar.signOut': '退出登录',
  'dashboard.title': '仪表板', 'dashboard.subtitle': '迁移平台概览',
  'dashboard.loading': '加载仪表板...', 'dashboard.loadFailed': '加载仪表板数据失败。',
  'dashboard.connections': '连接', 'dashboard.assessments': '评估',
  'dashboard.migrations': '迁移', 'dashboard.codeConversions': '代码转换',
  'dashboard.connected': '已连接', 'dashboard.done': '完成', 'dashboard.running': '运行中',
  'dashboard.failed': '失败', 'dashboard.scheduled': '已计划', 'dashboard.batches': '批次',
  'dashboard.src': '源', 'dashboard.tgt': '目标',
  'dashboard.assessmentDiscovery': '评估发现', 'dashboard.viewAll': '查看全部',
  'dashboard.tables': '表', 'dashboard.views': '视图', 'dashboard.routines': '例程',
  'dashboard.totalDataVolume': '总数据量', 'dashboard.migrationStatus': '迁移状态',
  'dashboard.completed': '已完成', 'dashboard.scheduled2': '已计划',
  'dashboard.recentActivity': '最近活动', 'dashboard.copyHistory': '复制历史',
  'dashboard.noRecentActivity': '无最近活动',
  'dashboard.name': '名称', 'dashboard.status': '状态', 'dashboard.size': '大小',
  'dashboard.started': '开始', 'dashboard.pathway': '路径', 'dashboard.created': '创建',
  'dashboard.table': '表', 'dashboard.rows': '行',
  'connections.title': '数据连接', 'connections.count': '连接',
  'connections.search': '搜索', 'connections.new': '+ 新建',
  'connections.sourceConnection': '源连接', 'connections.targetConnection': '目标连接',
  'connections.loading': '加载连接...', 'connections.retry': '重试',
  'connections.noConnections': '未找到连接', 'connections.createFirst': '创建第一个连接',
  'connections.name': '名称', 'connections.type': '类型', 'connections.database': '数据库',
  'connections.createdBy': '创建者', 'connections.connectionStatus': '连接状态',
  'connections.lastTestedAt': '最后测试', 'connections.testConnection': '测试连接',
  'connections.updateConnection': '更新连接', 'connections.deleteConnection': '删除连接',
  'connections.deleteConfirmTitle': '删除连接',
  'connections.deleteConfirmMsg': '确定要删除此连接吗？此操作无法撤消。',
  'connections.cancel': '取消', 'connections.connectionSuccessful': '连接成功',
  'connections.connectionFailed': '连接失败', 'connections.message': '消息',
  'connections.details': '详情', 'connections.troubleshooting': '故障排除提示',
  'connections.close': '关闭', 'connections.showing': '显示', 'connections.of': '/',
  'connections.rowsPerPage': '每页行数:', 'connections.connected': '已连接',
  'connections.disconnected': '已断开', 'connections.testing': '测试中',
  'assessments.title': '评估', 'assessments.new': '+ 新建', 'assessments.search': '搜索评估',
  'assessments.name': '名称', 'assessments.status': '状态', 'assessments.datasets': '数据集',
  'assessments.tables': '表', 'assessments.totalSize': '总大小',
  'assessments.startedAt': '开始时间', 'assessments.completedAt': '完成时间',
  'assessments.run': '运行评估', 'assessments.viewLogs': '查看日志',
  'assessments.viewReport': '查看报告', 'assessments.downloadReport': '下载报告',
  'assessments.edit': '编辑评估', 'assessments.delete': '删除评估',
  'assessments.deleteConfirm': '删除评估',
  'assessments.deleteConfirmMsg': '确定要删除此评估吗？此操作无法撤消。',
  'assessments.cancel': '取消', 'assessments.noAssessments': '暂无评估',
  'assessments.noAssessmentsDesc': '创建您的第一个BigQuery评估来分析数据',
  'assessments.createFirst': '创建第一个评估', 'assessments.loading': '加载评估中...',
  'assessments.started': '评估已开始', 'assessments.completed': '已完成',
  'assessments.failed': '失败', 'assessments.pending': '待处理',
  'assessments.rowsPerPage': '每页行数:', 'assessments.showing': '显示',
  'common.of': '/', 'common.retry': '重试',
  'migrations.title': '数据迁移', 'migrations.count': '迁移',
  'migrations.search': '搜索', 'migrations.new': '+ 新建', 'migrations.create': '创建',
  'migrations.loading': '加载迁移...', 'migrations.noMigrations': '未找到迁移',
  'migrations.createFirst': '创建第一个迁移',
  'migrations.name': '名称', 'migrations.source': '源', 'migrations.destination': '目标',
  'migrations.createdBy': '创建者', 'migrations.status': '状态', 'migrations.lastRunAt': '最后运行',
  'migrations.runMigration': '运行迁移', 'migrations.cancelMigration': '取消迁移',
  'migrations.viewLogs': '查看日志', 'migrations.editMigration': '编辑迁移',
  'migrations.deleteMigration': '删除迁移', 'migrations.deleteConfirmTitle': '删除迁移',
  'migrations.deleteConfirmMsg': '确定要删除此迁移吗？此操作无法撤消。',
  'migrations.cancel': '取消', 'migrations.restartTitle': '重启迁移',
  'migrations.restartMsg': '从头开始？所有进度将被清除。', 'migrations.restartBtn': '重启迁移',
  'migrations.cancelTitle': '取消迁移', 'migrations.cancelMsg': '迁移将停止。',
  'migrations.keepRunning': '继续运行', 'migrations.updateTitle': '更新迁移',
  'migrations.migrationName': '迁移名称', 'migrations.saveChanges': '保存更改',
  'migrations.showing': '显示', 'migrations.of': '/', 'migrations.rowsPerPage': '每页行数:',
  'migrations.migrationLogs': '迁移日志', 'migrations.loadingLogs': '加载日志...',
  'migrations.failedToLoadLogs': '加载日志失败', 'migrations.migration': '迁移',
  'migrations.success': '成功', 'migrations.ready': '就绪', 'migrations.paused': '已暂停',
  'migrations.cancelled': '已取消',
  'jobs.title': '任务', 'jobs.subtitle': '后台任务和操作',
  'jobs.loading': '加载任务...', 'jobs.noJobs': '没有任务',
  'jobs.all': '全部', 'jobs.running': '运行中', 'jobs.completed': '已完成',
  'jobs.failed': '失败', 'jobs.pending': '待处理',
  'jobs.name': '名称', 'jobs.type': '类型', 'jobs.status': '状态',
  'jobs.progress': '进度', 'jobs.startedAt': '开始时间', 'jobs.duration': '持续时间',
  'jobs.search': '搜索任务',
  'validation.title': '数据验证', 'validation.loading': '加载中...',
  'validation.createValidation': '创建验证', 'validation.noRuns': '没有验证运行',
  'validation.all': '全部', 'validation.pending': '待处理', 'validation.running': '运行中',
  'validation.completed': '已完成', 'validation.failed': '失败',
  'validation.rowsPerPage': '每页行数:', 'validation.showing': '显示',
  'common.search': '搜索', 'common.cancel': '取消', 'common.close': '关闭',
  'common.delete': '删除', 'common.edit': '编辑', 'common.save': '保存',
  'common.loading': '加载中...', 'common.noData': '无数据',
  'common.showing': '显示', 'common.rowsPerPage': '每页行数:',
  'common.never': '从未', 'common.justNow': '刚刚',
  // Profile
  'profile.title': '我的资料', 'profile.subtitle': '管理您的账户设置和偏好',
  'profile.userInfo': '用户信息', 'profile.username': '用户名', 'profile.role': '角色',
  'profile.theme': '主题', 'profile.language': '语言', 'profile.preferences': '偏好设置',
  'profile.selectLanguage': '选择语言', 'profile.changePassword': '修改密码',
  'profile.currentPassword': '当前密码', 'profile.newPassword': '新密码',
  'profile.confirmPassword': '确认密码', 'profile.updatePassword': '更新密码',
  'profile.passwordMismatch': '密码不匹配', 'profile.passwordTooShort': '密码至少需要6个字符',
  'profile.passwordChanged': '密码更新成功',
  'profile.activity': '活动概览',
  'admin.settingsDesc': '管理设置（仅管理员）',
  'admin.targets': '目标', 'admin.targetsDesc': '目标数据库连接管理',
  'admin.awsAccounts': 'AWS 账户', 'admin.awsAccountsDesc': 'AWS 账户管理界面',
  'admin.users': '用户', 'admin.usersDesc': '用户管理界面',
  'admin.dataConnections': '数据连接', 'admin.sources': '源',
  'validation.subtitle': '迁移后数据完整性验证',
  // Converter
  'converter.title': '代码转换器', 'converter.subtitle': '在不同方言之间转换SQL和数据库代码',
  'converter.sourceDialect': '源方言', 'converter.targetDialect': '目标方言',
  'converter.assetType': '资产类型', 'converter.assetName': '资产名称',
  'converter.bedrockModel': 'Bedrock 模型', 'converter.promptTemplate': '提示模板',
  'converter.localFiles': '本地文件', 'converter.maxRetries': '最大重试次数',
  'converter.sourceCode': '源代码', 'converter.convertedCode': '转换后代码',
  'converter.convert': '转换', 'converter.converting': '转换中…',
  'converter.pastePlaceholder': '在此粘贴您的SQL或数据库代码…',
  'converter.conversionHistory': '转换历史',
  'converter.sourceConnection': '源连接', 'converter.targetConnection': '目标连接',
  // Copy History
  'copyHistory.title': '复制历史', 'copyHistory.searchPlaceholder': '按迁移或表搜索...',
  'copyHistory.allStatus': '全部状态', 'copyHistory.completed': '已完成',
  'copyHistory.running': '运行中', 'copyHistory.failed': '失败',
  'copyHistory.loading': '加载复制历史...', 'copyHistory.noRecords': '没有COPY记录',
  'copyHistory.noRecordsDesc': '执行迁移时COPY命令将显示在此处。',
  'copyHistory.migration': '迁移', 'copyHistory.table': '表', 'copyHistory.status': '状态',
  'copyHistory.rows': '行', 'copyHistory.size': '大小', 'copyHistory.duration': '持续时间',
  'copyHistory.startedAt': '开始时间', 'copyHistory.format': '格式',
  'copyHistory.details': 'COPY命令详情', 'copyHistory.started': '开始',
  'copyHistory.completed2': '完成', 'copyHistory.rowsLoaded': '已加载行数',
  'copyHistory.bytesLoaded': '已加载字节', 'copyHistory.compression': '压缩',
  'copyHistory.sourceUri': '源URI', 'copyHistory.copyCommand': 'COPY命令',
  'copyHistory.error': '错误', 'copyHistory.errorDetails': '错误详情',
  'copyHistory.showing': '显示', 'copyHistory.of': '/',
  'copyHistory.rowsPerPage': '每页行数:', 'copyHistory.page': '页',
  // Task History
  'taskHistory.title': '任务历史', 'taskHistory.searchPlaceholder': '按迁移、表或ARN搜索...',
  'taskHistory.allStatus': '全部状态', 'taskHistory.completed': '已完成',
  'taskHistory.running': '运行中', 'taskHistory.failed': '失败', 'taskHistory.agentOffline': '代理离线',
  'taskHistory.loading': '加载任务历史...', 'taskHistory.noRecords': '没有DataSync任务',
  'taskHistory.noRecordsDesc': '通过Path B执行迁移时DataSync任务将显示在此处。',
  'taskHistory.migration': '迁移', 'taskHistory.table': '表', 'taskHistory.status': '状态',
  'taskHistory.files': '文件', 'taskHistory.size': '大小', 'taskHistory.duration': '持续时间',
  'taskHistory.agentIp': '代理IP', 'taskHistory.startedAt': '开始时间',
  'taskHistory.details': 'DataSync任务详情', 'taskHistory.taskType': '任务类型',
  'taskHistory.started': '开始', 'taskHistory.completed2': '完成',
  'taskHistory.filesTransferred': '已传输文件', 'taskHistory.bytesTransferred': '已传输字节',
  'taskHistory.source': '源', 'taskHistory.destination': '目标',
  'taskHistory.taskArn': '任务ARN', 'taskHistory.executionArn': '执行ARN',
  'taskHistory.agentArn': '代理ARN', 'taskHistory.error': '错误', 'taskHistory.errorDetails': '错误详情',
  'taskHistory.showing': '显示', 'taskHistory.of': '/',
  'taskHistory.rowsPerPage': '每页行数:', 'taskHistory.page': '页',
  // Validation extra
  'validation.passed': '通过', 'validation.active': '活跃',
  'validation.newValidation': '新建验证', 'validation.createStart': '创建并开始',
  'validation.newRun': '新建验证运行', 'validation.migration': '迁移',
  'validation.selectMigration': '选择迁移', 'validation.tables': '表',
  'validation.selectTables': '选择表...', 'validation.allTablesSelected': '已选择所有表',
  'validation.selectAll': '全选', 'validation.checksPerTable': '每表验证项',
  'validation.totalRows': '总行数', 'validation.recordsToValidate': '待验证记录',
  'validation.bedrockModel': 'Bedrock模型（可选）', 'validation.noneSkipAi': '无（跳过AI分析）',
  'validation.loadingModels': '加载模型中...', 'validation.loadingMigration': '加载迁移详情...',
  'validation.creating': '创建中…', 'validation.deleteConfirm': '删除此验证运行？此操作无法撤消。',
  'validation.noRunsDesc': '没有验证运行。点击"新建验证"开始。',
  'validation.id': 'ID', 'validation.progress': '进度', 'validation.started': '开始',
  'validation.duration': '持续时间', 'validation.actions': '操作',
  // Workspaces
  'workspaces.title': '工作区', 'workspaces.createWorkspace': '创建工作区',
  'workspaces.pinned': '已固定', 'workspaces.noPinned': '没有固定的工作区',
  'workspaces.searchPlaceholder': '搜索工作区', 'workspaces.selectPrompt': '选择工作区查看分析',
  'workspaces.reAnalyze': '重新分析', 'workspaces.overview': '概览',
  'workspaces.sourceConnections': '源连接', 'workspaces.targetConnections': '目标连接',
  'workspaces.compatibilityCheck': '兼容性检查', 'workspaces.codeConverter': '代码转换器',
  'workspaces.migrationJobs': '迁移任务', 'workspaces.loading': '加载工作区...',
  'workspaces.loadingAnalysis': '加载分析...', 'workspaces.noAnalysis': '没有分析数据。点击重新分析开始。',
  'workspaces.name': '名称', 'workspaces.description': '描述（可选）',
  'workspaces.creating': '创建中...', 'workspaces.create': '创建',
  'workspaces.sourceType': '源类型', 'workspaces.targetType': '目标类型',
  'workspaces.datasets': '数据集', 'workspaces.tables': '表', 'workspaces.totalRecords': '总记录',
  'workspaces.topTables': '按行数排名的表', 'workspaces.noTableData': '没有表数据。运行评估以填充。',
  'workspaces.noAssessments': '此工作区没有评估。',
  'workspaces.noMigrations': '此工作区没有迁移。',
  'workspaces.noSourceConns': '没有源连接', 'workspaces.noTargetConns': '没有目标连接',
  'workspaces.total': '总计', 'workspaces.completed': '已完成', 'workspaces.running': '运行中', 'workspaces.failed': '失败',
  'workspaces.migrationName': '迁移名称', 'workspaces.pathway': '路径',
  'workspaces.stage': '阶段', 'workspaces.progress': '进度', 'workspaces.sourceTarget': '源 → 目标',
  'workspaces.duration': '持续时间', 'workspaces.created': '创建',
  // Query History
  'queryHistory.subtitle': '对数据库执行的所有查询的历史记录',
  'queryHistory.searchPlaceholder': '搜索查询...', 'queryHistory.allStatus': '全部状态',
  'queryHistory.success': '成功', 'queryHistory.failed': '失败',
  'queryHistory.allDatabases': '全部数据库', 'queryHistory.loading': '加载查询历史...',
  'queryHistory.noRecords': '没有查询记录',
  'queryHistory.noRecordsDesc': '对数据库执行查询时，记录将显示在此处。',
  'queryHistory.query': '查询', 'queryHistory.database': '数据库', 'queryHistory.connection': '连接',
  'queryHistory.status': '状态', 'queryHistory.duration': '持续时间', 'queryHistory.rows': '行',
  'queryHistory.executedBy': '执行者', 'queryHistory.executedAt': '执行时间',
  'queryHistory.queryDetails': '查询详情', 'queryHistory.error': '错误',
  // Dynamic Tables
  'dynamicTables.subtitle': '监控迁移期间动态创建的表',
  'dynamicTables.searchPlaceholder': '搜索表...', 'dynamicTables.loading': '加载动态表...',
  'dynamicTables.noTables': '没有动态表',
  'dynamicTables.noTablesDesc': '迁移创建暂存或临时表时将显示在此处。',
  'dynamicTables.tableName': '表名', 'dynamicTables.schema': '架构',
  'dynamicTables.sourceTable': '源表', 'dynamicTables.migration': '迁移',
  'dynamicTables.rows': '行', 'dynamicTables.size': '大小',
  'dynamicTables.status': '状态', 'dynamicTables.createdAt': '创建时间',
  // Governance
  'governance.subtitle': '用于合规的平台操作审计追踪',
  'governance.searchPlaceholder': '搜索审计日志...', 'governance.allActions': '全部操作',
  'governance.create': '创建', 'governance.update': '更新', 'governance.delete': '删除',
  'governance.execute': '执行', 'governance.login': '登录',
  'governance.loading': '加载审计日志...', 'governance.noRecords': '没有审计记录',
  'governance.noRecordsDesc': '执行平台操作时审计记录将显示在此处。',
  'governance.action': '操作', 'governance.resource': '资源', 'governance.resourceName': '资源名称',
  'governance.performedBy': '执行者', 'governance.status': '状态',
  'governance.ipAddress': 'IP地址', 'governance.timestamp': '时间',
  'governance.auditDetails': '审计详情', 'governance.details': '详情',
};

const ja: TranslationMap = {
  ...en,
  'nav.dashboard': 'ダッシュボード', 'nav.workspaces': 'ワークスペース', 'nav.connections': '接続',
  'nav.assessments': '評価', 'nav.migrations': '移行', 'nav.jobs': 'ジョブ',
  'nav.converter': 'コード変換', 'nav.validations': 'データ検証', 'nav.monitoring': 'モニタリング',
  'nav.admin': '管理', 'nav.schemaAnalysis': 'スキーマ分析', 'nav.compatibilityCheck': '互換性チェック',
  'nav.assessmentReports': '評価レポート', 'nav.dataProfiling': 'データプロファイリング',
  'nav.running': '実行中', 'nav.queued': 'キュー待ち', 'nav.history': '履歴',
  'nav.quickConvert': 'クイック変換', 'nav.batch': 'バッチ',
  'nav.queryHistory': 'クエリ履歴', 'nav.copyHistory': 'コピー履歴',
  'nav.taskHistory': 'タスク履歴', 'nav.dynamicTables': '動的テーブル', 'nav.governance': 'ガバナンス',
  'sidebar.darkMode': 'ダークモード', 'sidebar.lightMode': 'ライトモード', 'sidebar.language': '言語',
  'sidebar.myProfile': 'マイプロフィール', 'sidebar.support': 'サポート', 'sidebar.documentation': 'ドキュメント',
  'sidebar.privacyNotice': 'プライバシー', 'sidebar.signOut': 'サインアウト',
  'dashboard.title': 'ダッシュボード', 'dashboard.subtitle': '移行プラットフォームの概要',
  'dashboard.loading': 'ダッシュボード読み込み中...', 'dashboard.loadFailed': 'ダッシュボードの読み込みに失敗しました。',
  'dashboard.connections': '接続', 'dashboard.assessments': '評価',
  'dashboard.migrations': '移行', 'dashboard.codeConversions': 'コード変換',
  'dashboard.connected': '接続済み', 'dashboard.done': '完了', 'dashboard.running': '実行中',
  'dashboard.failed': '失敗', 'dashboard.scheduled': '予定', 'dashboard.batches': 'バッチ',
  'dashboard.src': 'ソース', 'dashboard.tgt': 'ターゲット',
  'dashboard.assessmentDiscovery': '評価検出', 'dashboard.viewAll': 'すべて表示',
  'dashboard.tables': 'テーブル', 'dashboard.views': 'ビュー', 'dashboard.routines': 'ルーチン',
  'dashboard.totalDataVolume': '総データ量', 'dashboard.migrationStatus': '移行ステータス',
  'dashboard.completed': '完了', 'dashboard.recentActivity': '最近のアクティビティ',
  'dashboard.copyHistory': 'コピー履歴', 'dashboard.noRecentActivity': '最近のアクティビティなし',
  'dashboard.name': '名前', 'dashboard.status': 'ステータス', 'dashboard.size': 'サイズ',
  'dashboard.started': '開始', 'dashboard.pathway': 'パスウェイ', 'dashboard.created': '作成',
  'dashboard.table': 'テーブル', 'dashboard.rows': '行',
  'connections.title': 'データ接続', 'connections.count': '接続',
  'connections.search': '検索', 'connections.new': '+ 新規',
  'connections.loading': '接続読み込み中...', 'connections.noConnections': '接続が見つかりません',
  'connections.createFirst': '最初の接続を作成', 'connections.name': '名前',
  'connections.type': 'タイプ', 'connections.database': 'データベース',
  'connections.createdBy': '作成者', 'connections.connectionStatus': '接続状態',
  'connections.lastTestedAt': '最終テスト', 'connections.rowsPerPage': '表示行数:',
  'assessments.title': '評価', 'assessments.new': '+ 新規', 'assessments.loading': '評価読み込み中...',
  'assessments.noAssessments': '評価がありません', 'assessments.createFirst': '最初の評価を作成',
  'assessments.rowsPerPage': '表示行数:', 'common.of': '/', 'common.retry': '再試行',
  'migrations.title': 'データ移行', 'migrations.loading': '移行読み込み中...',
  'migrations.noMigrations': '移行が見つかりません', 'migrations.createFirst': '最初の移行を作成',
  'migrations.rowsPerPage': '表示行数:',
  'jobs.title': 'ジョブ', 'jobs.loading': 'ジョブ読み込み中...', 'jobs.noJobs': 'ジョブなし',
  'validation.title': 'データ検証', 'validation.loading': '読み込み中...',
  'common.search': '検索', 'common.cancel': 'キャンセル', 'common.close': '閉じる',
  'common.loading': '読み込み中...', 'common.never': 'なし', 'common.justNow': 'たった今',
};

const fr: TranslationMap = {
  ...en,
  'nav.dashboard': 'Tableau de bord', 'nav.workspaces': 'Espaces', 'nav.connections': 'Connexions',
  'nav.assessments': 'Évaluations', 'nav.migrations': 'Migrations', 'nav.jobs': 'Tâches',
  'nav.converter': 'Convertisseur', 'nav.validations': 'Validation', 'nav.monitoring': 'Surveillance',
  'nav.admin': 'Admin', 'nav.schemaAnalysis': 'Analyse de schéma',
  'nav.compatibilityCheck': 'Vérification de compatibilité',
  'nav.assessmentReports': "Rapports d'évaluation", 'nav.dataProfiling': 'Profilage de données',
  'nav.running': 'En cours', 'nav.queued': 'En attente', 'nav.history': 'Historique',
  'nav.quickConvert': 'Conversion rapide', 'nav.batch': 'Lot',
  'nav.queryHistory': 'Historique des requêtes', 'nav.copyHistory': 'Historique des copies',
  'nav.taskHistory': 'Historique des tâches', 'nav.dynamicTables': 'Tables dynamiques',
  'nav.governance': 'Gouvernance',
  'sidebar.darkMode': 'Mode sombre', 'sidebar.lightMode': 'Mode clair', 'sidebar.language': 'Langue',
  'sidebar.myProfile': 'Mon profil', 'sidebar.support': 'Support', 'sidebar.documentation': 'Documentation',
  'sidebar.privacyNotice': 'Confidentialité', 'sidebar.signOut': 'Déconnexion',
  'dashboard.title': 'Tableau de bord', 'dashboard.subtitle': 'Aperçu de votre plateforme de migration',
  'dashboard.loading': 'Chargement...', 'dashboard.loadFailed': 'Échec du chargement.',
  'dashboard.connections': 'Connexions', 'dashboard.assessments': 'Évaluations',
  'dashboard.migrations': 'Migrations', 'dashboard.codeConversions': 'Conversions de code',
  'dashboard.connected': 'connecté', 'dashboard.done': 'terminé', 'dashboard.running': 'en cours',
  'dashboard.failed': 'échoué', 'dashboard.scheduled': 'planifié', 'dashboard.batches': 'lots',
  'dashboard.assessmentDiscovery': 'Découverte', 'dashboard.viewAll': 'Tout voir',
  'dashboard.tables': 'Tables', 'dashboard.views': 'Vues', 'dashboard.routines': 'Routines',
  'dashboard.totalDataVolume': 'Volume total', 'dashboard.migrationStatus': 'Statut des migrations',
  'dashboard.completed': 'Terminé', 'dashboard.recentActivity': 'Activité récente',
  'dashboard.copyHistory': 'Historique des copies', 'dashboard.noRecentActivity': 'Aucune activité récente',
  'connections.title': 'Connexions de données', 'connections.loading': 'Chargement...',
  'connections.noConnections': 'Aucune connexion', 'connections.createFirst': 'Créer une connexion',
  'assessments.title': 'Évaluations', 'assessments.loading': 'Chargement...',
  'assessments.noAssessments': 'Aucune évaluation', 'assessments.createFirst': 'Créer une évaluation',
  'migrations.title': 'Migrations de données', 'migrations.loading': 'Chargement...',
  'migrations.noMigrations': 'Aucune migration', 'migrations.createFirst': 'Créer une migration',
  'jobs.title': 'Tâches', 'jobs.loading': 'Chargement...', 'jobs.noJobs': 'Aucune tâche',
  'validation.title': 'Validation des données', 'validation.loading': 'Chargement...',
  'common.search': 'Rechercher', 'common.cancel': 'Annuler', 'common.close': 'Fermer',
  'common.of': 'sur', 'common.retry': 'Réessayer', 'common.loading': 'Chargement...',
};

const es: TranslationMap = {
  ...en,
  'nav.dashboard': 'Panel', 'nav.workspaces': 'Espacios', 'nav.connections': 'Conexiones',
  'nav.assessments': 'Evaluaciones', 'nav.migrations': 'Migraciones', 'nav.jobs': 'Trabajos',
  'nav.converter': 'Convertidor', 'nav.validations': 'Validación', 'nav.monitoring': 'Monitoreo',
  'nav.admin': 'Admin',
  'sidebar.darkMode': 'Modo oscuro', 'sidebar.lightMode': 'Modo claro', 'sidebar.language': 'Idioma',
  'sidebar.myProfile': 'Mi perfil', 'sidebar.support': 'Soporte', 'sidebar.documentation': 'Documentación',
  'sidebar.privacyNotice': 'Privacidad', 'sidebar.signOut': 'Cerrar sesión',
  'dashboard.title': 'Panel', 'dashboard.subtitle': 'Resumen de su plataforma de migración',
  'dashboard.loading': 'Cargando...', 'dashboard.loadFailed': 'Error al cargar.',
  'dashboard.connections': 'Conexiones', 'dashboard.assessments': 'Evaluaciones',
  'dashboard.migrations': 'Migraciones', 'dashboard.codeConversions': 'Conversiones',
  'dashboard.connected': 'conectado', 'dashboard.done': 'hecho', 'dashboard.running': 'ejecutando',
  'dashboard.failed': 'fallido', 'dashboard.viewAll': 'Ver todo',
  'dashboard.tables': 'Tablas', 'dashboard.views': 'Vistas', 'dashboard.routines': 'Rutinas',
  'dashboard.totalDataVolume': 'Volumen total', 'dashboard.migrationStatus': 'Estado de migraciones',
  'dashboard.completed': 'Completado', 'dashboard.recentActivity': 'Actividad reciente',
  'dashboard.noRecentActivity': 'Sin actividad reciente',
  'connections.title': 'Conexiones', 'connections.loading': 'Cargando...',
  'assessments.title': 'Evaluaciones', 'assessments.loading': 'Cargando...',
  'migrations.title': 'Migraciones', 'migrations.loading': 'Cargando...',
  'jobs.title': 'Trabajos', 'jobs.loading': 'Cargando...',
  'validation.title': 'Validación', 'validation.loading': 'Cargando...',
  'common.search': 'Buscar', 'common.cancel': 'Cancelar', 'common.close': 'Cerrar',
  'common.of': 'de', 'common.retry': 'Reintentar', 'common.loading': 'Cargando...',
};

const de: TranslationMap = {
  ...en,
  'nav.dashboard': 'Dashboard', 'nav.workspaces': 'Arbeitsbereiche', 'nav.connections': 'Verbindungen',
  'nav.assessments': 'Bewertungen', 'nav.migrations': 'Migrationen', 'nav.jobs': 'Aufgaben',
  'nav.converter': 'Code-Konverter', 'nav.validations': 'Datenvalidierung', 'nav.monitoring': 'Überwachung',
  'nav.admin': 'Admin',
  'sidebar.darkMode': 'Dunkelmodus', 'sidebar.lightMode': 'Hellmodus', 'sidebar.language': 'Sprache',
  'sidebar.myProfile': 'Mein Profil', 'sidebar.support': 'Support', 'sidebar.documentation': 'Dokumentation',
  'sidebar.privacyNotice': 'Datenschutz', 'sidebar.signOut': 'Abmelden',
  'dashboard.title': 'Dashboard', 'dashboard.subtitle': 'Übersicht Ihrer Migrationsplattform',
  'dashboard.loading': 'Laden...', 'dashboard.loadFailed': 'Laden fehlgeschlagen.',
  'dashboard.connections': 'Verbindungen', 'dashboard.assessments': 'Bewertungen',
  'dashboard.migrations': 'Migrationen', 'dashboard.codeConversions': 'Code-Konvertierungen',
  'dashboard.viewAll': 'Alle anzeigen', 'dashboard.tables': 'Tabellen', 'dashboard.views': 'Ansichten',
  'dashboard.routines': 'Routinen', 'dashboard.totalDataVolume': 'Gesamtdatenvolumen',
  'dashboard.migrationStatus': 'Migrationsstatus', 'dashboard.completed': 'Abgeschlossen',
  'dashboard.recentActivity': 'Letzte Aktivität', 'dashboard.noRecentActivity': 'Keine Aktivität',
  'connections.title': 'Datenverbindungen', 'connections.loading': 'Laden...',
  'assessments.title': 'Bewertungen', 'assessments.loading': 'Laden...',
  'migrations.title': 'Datenmigrationen', 'migrations.loading': 'Laden...',
  'jobs.title': 'Aufgaben', 'jobs.loading': 'Laden...',
  'validation.title': 'Datenvalidierung', 'validation.loading': 'Laden...',
  'common.search': 'Suchen', 'common.cancel': 'Abbrechen', 'common.close': 'Schließen',
  'common.of': 'von', 'common.retry': 'Wiederholen', 'common.loading': 'Laden...',
};

const pt: TranslationMap = {
  ...en,
  'nav.dashboard': 'Painel', 'nav.workspaces': 'Espaços', 'nav.connections': 'Conexões',
  'nav.assessments': 'Avaliações', 'nav.migrations': 'Migrações', 'nav.jobs': 'Tarefas',
  'nav.converter': 'Conversor', 'nav.validations': 'Validação', 'nav.monitoring': 'Monitoramento',
  'nav.admin': 'Admin',
  'sidebar.darkMode': 'Modo escuro', 'sidebar.lightMode': 'Modo claro', 'sidebar.language': 'Idioma',
  'sidebar.myProfile': 'Meu perfil', 'sidebar.support': 'Suporte', 'sidebar.documentation': 'Documentação',
  'sidebar.privacyNotice': 'Privacidade', 'sidebar.signOut': 'Sair',
  'dashboard.title': 'Painel', 'dashboard.subtitle': 'Visão geral da plataforma de migração',
  'dashboard.loading': 'Carregando...', 'dashboard.loadFailed': 'Falha ao carregar.',
  'dashboard.connections': 'Conexões', 'dashboard.assessments': 'Avaliações',
  'dashboard.migrations': 'Migrações', 'dashboard.codeConversions': 'Conversões',
  'dashboard.viewAll': 'Ver tudo', 'dashboard.tables': 'Tabelas', 'dashboard.views': 'Visões',
  'dashboard.routines': 'Rotinas', 'dashboard.totalDataVolume': 'Volume total',
  'dashboard.migrationStatus': 'Status das migrações', 'dashboard.completed': 'Concluído',
  'dashboard.recentActivity': 'Atividade recente', 'dashboard.noRecentActivity': 'Sem atividade',
  'common.search': 'Pesquisar', 'common.cancel': 'Cancelar', 'common.close': 'Fechar',
  'common.of': 'de', 'common.retry': 'Tentar novamente', 'common.loading': 'Carregando...',
};

const hi: TranslationMap = {
  ...en,
  'nav.dashboard': 'डैशबोर्ड', 'nav.workspaces': 'वर्कस्पेस', 'nav.connections': 'कनेक्शन',
  'nav.assessments': 'मूल्यांकन', 'nav.migrations': 'माइग्रेशन', 'nav.jobs': 'कार्य',
  'nav.converter': 'कोड कनवर्टर', 'nav.validations': 'डेटा सत्यापन', 'nav.monitoring': 'निगरानी',
  'nav.admin': 'एडमिन',
  'sidebar.darkMode': 'डार्क मोड', 'sidebar.lightMode': 'लाइट मोड', 'sidebar.language': 'भाषा',
  'sidebar.myProfile': 'मेरी प्रोफ़ाइल', 'sidebar.support': 'सहायता', 'sidebar.documentation': 'दस्तावेज़',
  'sidebar.privacyNotice': 'गोपनीयता', 'sidebar.signOut': 'साइन आउट',
  'dashboard.title': 'डैशबोर्ड', 'dashboard.subtitle': 'माइग्रेशन प्लेटफ़ॉर्म का अवलोकन',
  'dashboard.loading': 'डैशबोर्ड लोड हो रहा है...', 'dashboard.loadFailed': 'डैशबोर्ड लोड करने में विफल।',
  'dashboard.connections': 'कनेक्शन', 'dashboard.assessments': 'मूल्यांकन',
  'dashboard.migrations': 'माइग्रेशन', 'dashboard.codeConversions': 'कोड रूपांतरण',
  'dashboard.viewAll': 'सभी देखें', 'dashboard.tables': 'टेबल', 'dashboard.views': 'व्यू',
  'dashboard.routines': 'रूटीन', 'dashboard.totalDataVolume': 'कुल डेटा वॉल्यूम',
  'dashboard.migrationStatus': 'माइग्रेशन स्थिति', 'dashboard.completed': 'पूर्ण',
  'dashboard.recentActivity': 'हाल की गतिविधि', 'dashboard.noRecentActivity': 'कोई गतिविधि नहीं',
  'common.search': 'खोजें', 'common.cancel': 'रद्द करें', 'common.close': 'बंद करें',
  'common.of': 'में से', 'common.retry': 'पुनः प्रयास', 'common.loading': 'लोड हो रहा है...',
};

const translations: Translations = { en, ko, zh, ja, fr, es, de, pt, hi };

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('datamiq-language');
    return (saved as LanguageCode) || 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('datamiq-language', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
